const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");

const {
  applyCompileDraft,
  createCompileDraft,
  routeRecordsForRole
} = require("../dist/core/compiler.js");
const { appendRecord, ensureStore, readAllRecords } = require("../dist/core/store.js");

function tempRoot() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "wikiwiki-compile-"));
  writeFile(root, "README.md", "# Test repo\n");
  writeFile(root, "src/core/store.ts", "export {}\n");
  writeFile(root, "src/cli/commands/compile.ts", "export {}\n");
  return root;
}

function writeFile(root, file, content) {
  const fullPath = path.join(root, file);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, "utf8");
}

function seedRecords(root) {
  ensureStore(root);
  appendRecord(root, "concept", {
    type: "concept",
    id: "concept_product",
    source: "agent",
    authority: "agent",
    confidence: "high",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    name: "Product loop",
    summary: "The user loop explains how people experience the product.",
    details: "",
    files: ["README.md"],
    tags: ["ux", "product"]
  });
  appendRecord(root, "concept", {
    type: "concept",
    id: "concept_architecture",
    source: "agent",
    authority: "agent",
    confidence: "high",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    name: "Record store",
    summary: "Records are stored as append-only JSONL.",
    details: "",
    files: ["src/core/store.ts"],
    tags: ["dx", "architecture", "core"]
  });
  appendRecord(root, "decision", {
    type: "decision",
    id: "decision_shared",
    source: "manual",
    authority: "user",
    confidence: "high",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    title: "Keep records local",
    context: "Agents need auditable context.",
    decision: "Use repo-local records.",
    consequences: "Docs can be regenerated.",
    files: ["README.md"],
    tags: []
  });
  appendRecord(root, "symbol", {
    type: "symbol",
    id: "symbol_compile",
    source: "agent",
    authority: "agent",
    confidence: "high",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    name: "createCompileDraft",
    kind: "function",
    file: "src/cli/commands/compile.ts",
    summary: "Creates human wiki draft packets."
  });
}

test("routeRecordsForRole routes UX, DX, and shared records", () => {
  const root = tempRoot();
  seedRecords(root);
  const records = readAllRecords(root);

  const uxIds = routeRecordsForRole(records, "ux").map((record) => record.id);
  const dxIds = routeRecordsForRole(records, "dx").map((record) => record.id);

  assert.ok(uxIds.includes("concept_product"));
  assert.ok(uxIds.includes("decision_shared"));
  assert.equal(uxIds.includes("concept_architecture"), false);
  assert.ok(dxIds.includes("concept_architecture"));
  assert.ok(dxIds.includes("decision_shared"));
  assert.ok(dxIds.includes("symbol_compile"));
});

test("createCompileDraft writes an all-role manifest and draft pages", () => {
  const root = tempRoot();
  seedRecords(root);

  const draft = createCompileDraft(root, "all");
  const manifest = JSON.parse(fs.readFileSync(draft.manifest_path, "utf8"));

  assert.equal(manifest.type, "compile-draft");
  assert.deepEqual(manifest.roles, ["ux", "dx"]);
  assert.ok(manifest.pages.some((page) => page.output_path === "wiki/human/ux/product-overview.md"));
  assert.ok(manifest.pages.some((page) => page.output_path === "wiki/human/dx/architecture.md"));
  assert.ok(fs.existsSync(path.join(draft.draft_path, "ux/product-overview.md")));
  assert.ok(fs.existsSync(path.join(draft.draft_path, "dx/architecture.md")));
});

test("applyCompileDraft publishes human wiki pages with provenance", () => {
  const root = tempRoot();
  seedRecords(root);
  const draft = createCompileDraft(root, "ux");

  const result = applyCompileDraft(root, draft.draft_id);
  const output = fs.readFileSync(path.join(root, "wiki/human/ux/product-overview.md"), "utf8");

  assert.equal(result.ok, true);
  assert.ok(result.rendered_files.includes("wiki/human/index.md"));
  assert.match(output, /Generated by Wikiwiki human compile/);
  assert.match(output, /## Sources/);
  assert.match(output, new RegExp(`Draft: \`${draft.draft_id}\``));
});

test("applyCompileDraft fails for missing drafts and inactive provenance records", () => {
  const root = tempRoot();
  seedRecords(root);
  const missingDraft = createCompileDraft(root, "ux");
  fs.rmSync(path.join(missingDraft.draft_path, "ux/product-overview.md"));

  assert.throws(
    () => applyCompileDraft(root, missingDraft.draft_id),
    /Draft page is missing/
  );

  const inactiveRoot = tempRoot();
  seedRecords(inactiveRoot);
  const inactiveDraft = createCompileDraft(inactiveRoot, "ux");
  appendRecord(inactiveRoot, "concept", {
    type: "concept",
    id: "concept_product",
    source: "agent",
    authority: "agent",
    confidence: "high",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-02T00:00:00.000Z",
    deleted_at: "2026-01-02T00:00:00.000Z",
    delete_reason: "test",
    name: "Product loop",
    summary: "The user loop explains how people experience the product.",
    details: "",
    files: ["README.md"],
    tags: ["ux", "product"]
  });

  assert.throws(
    () => applyCompileDraft(inactiveRoot, inactiveDraft.draft_id),
    /references inactive record/
  );
});
