import fs from "fs";
import path from "path";
import { readWikiwikiSiteTheme } from "./config";
import { articleMarkdownFileName } from "./articles";
import { articlePage, articlesPage } from "../templates/articlesPage";
import { decisionsPage } from "../templates/decisionsPage";
import { conceptsPage } from "../templates/conceptsPage";
import { devlogPage } from "../templates/devlogPage";
import { indexPage } from "../templates/indexPage";
import { linksPage } from "../templates/linksPage";
import { notesPage } from "../templates/notesPage";
import { symbolsPage } from "../templates/symbolsPage";
import { readAllRecords } from "./store";
import { wikiPath } from "./paths";
import { recordTypes, type AnyRecord } from "./schemas";

export const generatedNotice =
  "<!-- Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run `wk render`. -->";

export const wikiPageFileNames = [
  "index.md",
  "articles.md",
  "concepts.md",
  "decisions.md",
  "devlog.md",
  "notes.md",
  "symbols.md",
  "links.md"
] as const;

export type RenderedPage = {
  fileName: string;
  content: string;
};

export function buildWikiPages(root: string): RenderedPage[] {
  const records = readAllRecords(root);
  const theme = readWikiwikiSiteTheme(root);
  const repoName = theme.project_name?.trim() || path.basename(root);
  const description = theme.project_description?.trim() || "A project wiki generated from durable repo knowledge.";
  const sourceRecords = new Map<string, AnyRecord>();
  for (const type of recordTypes) {
    for (const record of records[type]) {
      sourceRecords.set(record.id, record);
    }
  }
  const pages: RenderedPage[] = [
    {
      fileName: "index.md",
      content: withNotice(indexPage(records, { repoName, description }))
    },
    {
      fileName: "articles.md",
      content: withNotice(articlesPage(records.article))
    },
    {
      fileName: "concepts.md",
      content: withNotice(conceptsPage(records.concept))
    },
    {
      fileName: "decisions.md",
      content: withNotice(decisionsPage(records.decision))
    },
    {
      fileName: "devlog.md",
      content: withNotice(devlogPage(records.event))
    },
    {
      fileName: "notes.md",
      content: withNotice(notesPage(records.note))
    },
    {
      fileName: "symbols.md",
      content: withNotice(symbolsPage(records.symbol))
    },
    {
      fileName: "links.md",
      content: withNotice(linksPage(records.link))
    }
  ];

  for (const article of records.article) {
    pages.push({
      fileName: `articles/${articleMarkdownFileName(article)}`,
      content: withNotice(articlePage(article, article.source_record_ids.map((id) => sourceRecords.get(id)).filter(isRecord)))
    });
  }

  return pages;
}

export function renderWiki(root: string): string[] {
  const pages = buildWikiPages(root);
  const outputPath = wikiPath(root);
  fs.mkdirSync(outputPath, { recursive: true });
  fs.rmSync(path.join(outputPath, "articles"), { recursive: true, force: true });

  return pages.map((page) => {
    const file = path.join(outputPath, page.fileName);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, page.content, "utf8");
    return file;
  });
}

function withNotice(content: string): string {
  return `${generatedNotice}\n\n${content.trimEnd()}\n`;
}

function isRecord(record: AnyRecord | undefined): record is AnyRecord {
  return record !== undefined;
}
