import fs from "fs";
import path from "path";
import { decisionsPage } from "../templates/decisionsPage";
import { conceptsPage } from "../templates/conceptsPage";
import { devlogPage } from "../templates/devlogPage";
import { indexPage } from "../templates/indexPage";
import { notesPage } from "../templates/notesPage";
import { readAllRecords } from "./store";
import { wikiPath } from "./paths";

export const generatedNotice =
  "<!-- Generated by Wikiwiki. Edit structured records instead. -->";

export type RenderedPage = {
  fileName: string;
  content: string;
};

export function buildWikiPages(root: string): RenderedPage[] {
  const records = readAllRecords(root);
  return [
    {
      fileName: "index.md",
      content: withNotice(indexPage(records))
    },
    {
      fileName: "concepts.md",
      content: withNotice(conceptsPage(records.concept))
    },
    {
      fileName: "decisions.md",
      content: withNotice(decisionsPage(records.decision))
    },
    {
      fileName: "devlog.md",
      content: withNotice(devlogPage(records.event))
    },
    {
      fileName: "notes.md",
      content: withNotice(notesPage(records.note))
    }
  ];
}

export function renderWiki(root: string): string[] {
  const pages = buildWikiPages(root);
  const outputPath = wikiPath(root);
  fs.mkdirSync(outputPath, { recursive: true });

  return pages.map((page) => {
    const file = path.join(outputPath, page.fileName);
    fs.writeFileSync(file, page.content, "utf8");
    return file;
  });
}

function withNotice(content: string): string {
  return `${generatedNotice}\n\n${content.trimEnd()}\n`;
}
