import fs from "fs";
import path from "path";
import { sitePath } from "./paths";
import { readAllRecords, type RecordsByType } from "./store";
import { type AnyRecord, type RecordType, recordTypes } from "./schemas";

export const siteGeneratedNotice =
  "<!-- Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run `wk site`. -->";

export const siteStaticPageFileNames = [
  "index.html",
  "concepts.html",
  "decisions.html",
  "devlog.html",
  "notes.html",
  "symbols.html",
  "links.html",
  "search.html"
] as const;

export type SiteFile = {
  fileName: string;
  content: string;
};

type Category = {
  type: RecordType;
  title: string;
  navLabel: string;
  fileName: string;
  description: string;
};

type SiteModel = {
  repoName: string;
  records: RecordsByType;
  flatRecords: AnyRecord[];
  hrefById: Map<string, string>;
  counts: Record<RecordType, number>;
};

type LayoutOptions = {
  model: SiteModel;
  fileName: string;
  title: string;
  description: string;
  active: string;
  body: string;
};

type RenderContext = {
  currentFile: string;
  hrefById: Map<string, string>;
};

type SearchEntry = {
  type: RecordType;
  id: string;
  title: string;
  summary: string;
  tags: string[];
  authority: string;
  confidence: string;
  url: string;
  text: string;
};

const categories: Category[] = [
  {
    type: "concept",
    title: "Concepts",
    navLabel: "Concepts",
    fileName: "concepts.html",
    description: "Durable explanations, domain terms, product ideas, and system concepts."
  },
  {
    type: "decision",
    title: "Decisions",
    navLabel: "Decisions",
    fileName: "decisions.html",
    description: "Product, architecture, workflow, and implementation decisions with rationale."
  },
  {
    type: "event",
    title: "Devlog",
    navLabel: "Devlog",
    fileName: "devlog.html",
    description: "Meaningful changes and development milestones in chronological context."
  },
  {
    type: "note",
    title: "Notes",
    navLabel: "Notes",
    fileName: "notes.html",
    description: "Lightweight facts, reminders, and working context."
  },
  {
    type: "symbol",
    title: "Symbols",
    navLabel: "Symbols",
    fileName: "symbols.html",
    description: "Important code symbols and where maintainers should look first."
  },
  {
    type: "link",
    title: "Links",
    navLabel: "Links",
    fileName: "links.html",
    description: "Relationships between records, files, generated docs, and source concepts."
  }
];

const categoryByType = new Map<RecordType, Category>(categories.map((category) => [category.type, category]));

export function buildSiteFiles(root: string): SiteFile[] {
  const records = readAllRecords(root);
  const model = createSiteModel(root, records);
  const files: SiteFile[] = [];

  files.push({
    fileName: "index.html",
    content: renderLayout({
      model,
      fileName: "index.html",
      title: `${model.repoName} Wiki`,
      description: "A generated, browseable wiki built from structured Wikiwiki records.",
      active: "home",
      body: renderHomePage(model)
    })
  });

  for (const category of categories) {
    files.push({
      fileName: category.fileName,
      content: renderLayout({
        model,
        fileName: category.fileName,
        title: category.title,
        description: category.description,
        active: category.type,
        body: renderCategoryPage(model, category)
      })
    });
  }

  files.push({
    fileName: "search.html",
    content: renderLayout({
      model,
      fileName: "search.html",
      title: "Search",
      description: "Search active Wikiwiki records without a backend.",
      active: "search",
      body: renderSearchPage()
    })
  });

  for (const record of model.flatRecords) {
    const fileName = recordHref(record);
    files.push({
      fileName,
      content: renderLayout({
        model,
        fileName,
        title: recordTitle(record),
        description: recordSummary(record),
        active: record.type,
        body: renderRecordPage(record, model, fileName)
      })
    });
  }

  files.push(
    { fileName: "assets/wikiwiki.css", content: siteCss() },
    { fileName: "assets/search-index.js", content: searchIndexJs(model) },
    { fileName: "assets/wikiwiki.js", content: siteJs() },
    { fileName: ".nojekyll", content: "" },
    { fileName: "site-manifest.json", content: `${JSON.stringify(siteManifest(model), null, 2)}\n` }
  );

  return files;
}

export function renderSite(root: string): string[] {
  const files = buildSiteFiles(root);
  const outputPath = sitePath(root);

  fs.rmSync(outputPath, { recursive: true, force: true });
  fs.mkdirSync(outputPath, { recursive: true });

  return files.map((file) => {
    const outputFile = path.join(outputPath, file.fileName);
    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
    fs.writeFileSync(outputFile, file.content, "utf8");
    return outputFile;
  });
}

function createSiteModel(root: string, records: RecordsByType): SiteModel {
  const flatRecords: AnyRecord[] = [];
  for (const type of recordTypes) {
    flatRecords.push(...records[type]);
  }
  flatRecords.sort(compareRecords);
  const hrefById = new Map(flatRecords.map((record) => [record.id, recordHref(record)]));
  const counts = Object.fromEntries(recordTypes.map((type) => [type, records[type].length])) as Record<RecordType, number>;

  return {
    repoName: path.basename(root),
    records,
    flatRecords,
    hrefById,
    counts
  };
}

function renderLayout(options: LayoutOptions): string {
  const prefix = relativePrefix(options.fileName);
  const searchHref = hrefFrom(options.fileName, "search.html");

  return `${siteGeneratedNotice}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="Wikiwiki">
  <title>${escapeHtml(options.title)} - Wikiwiki</title>
  <link rel="stylesheet" href="${prefix}assets/wikiwiki.css">
  <script src="${prefix}assets/search-index.js" defer></script>
  <script src="${prefix}assets/wikiwiki.js" defer></script>
</head>
<body>
  <a class="skip-link" href="#content">Skip to content</a>
  <div class="site-shell">
    <aside class="sidebar" aria-label="Wiki navigation">
      <a class="brand" href="${hrefFrom(options.fileName, "index.html")}" aria-label="Wiki home">
        <span class="brand-mark">wk</span>
        <span>
          <strong>${escapeHtml(options.model.repoName)}</strong>
          <small>Wikiwiki</small>
        </span>
      </a>
      <label class="sidebar-search">
        <span>Search</span>
        <input type="search" placeholder="Search records" data-site-search data-search-target="${searchHref}">
      </label>
      ${renderNav(options.model, options.fileName, options.active)}
    </aside>
    <main id="content" class="content">
      <header class="page-header">
        <p class="eyebrow">Generated Wikiwiki site</p>
        <h1>${escapeHtml(options.title)}</h1>
        <p>${escapeHtml(options.description)}</p>
      </header>
      ${options.body}
    </main>
  </div>
</body>
</html>
`;
}

function renderNav(model: SiteModel, currentFile: string, active: string): string {
  const categoryLinks = categories
    .map((category) => navLink(currentFile, category.fileName, category.navLabel, active === category.type, model.counts[category.type]))
    .join("\n");

  return `<nav class="nav">
  <p class="nav-heading">Start Here</p>
  ${navLink(currentFile, "index.html", "Home", active === "home")}
  ${navLink(currentFile, "search.html", "Search", active === "search")}
  <p class="nav-heading">Records</p>
  ${categoryLinks}
</nav>`;
}

function navLink(currentFile: string, targetFile: string, label: string, active: boolean, count?: number): string {
  const countHtml = typeof count === "number" ? `<span>${count}</span>` : "";
  const activeAttribute = active ? ` aria-current="page"` : "";
  return `<a class="nav-link${active ? " active" : ""}" href="${hrefFrom(currentFile, targetFile)}"${activeAttribute}>${escapeHtml(label)}${countHtml}</a>`;
}

function renderHomePage(model: SiteModel): string {
  const primaryCards = categories
    .slice(0, 4)
    .map((category) => sectionCard("index.html", category.fileName, category.title, category.description, model.counts[category.type]))
    .join("\n");
  const supportCards = categories
    .slice(4)
    .map((category) => sectionCard("index.html", category.fileName, category.title, category.description, model.counts[category.type]))
    .join("\n");
  const recentRecords = [...model.flatRecords]
    .sort((a, b) => recordTimestamp(b).localeCompare(recordTimestamp(a)) || recordTitle(a).localeCompare(recordTitle(b)))
    .slice(0, 6)
    .map((record) => recordCard(record, "index.html", model))
    .join("\n");

  return `<section class="hero-panel">
  <div>
    <p class="eyebrow">Start here</p>
    <h2>Browse the project knowledge without reading raw records.</h2>
    <p>Wikiwiki keeps JSONL and Markdown for agents, then generates this static site for humans. Links are plain HTML files, so the site works locally and on static hosts.</p>
  </div>
  <dl class="stats-grid">
    ${recordTypes.map((type) => `<div><dt>${escapeHtml(labelForType(type))}</dt><dd>${model.counts[type]}</dd></div>`).join("\n")}
  </dl>
</section>

<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Browse</p>
    <h2>Core Pages</h2>
  </div>
  <div class="card-grid">${primaryCards}</div>
</section>

<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Reference</p>
    <h2>Developer Context</h2>
  </div>
  <div class="card-grid compact">${supportCards}</div>
</section>

<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Latest</p>
    <h2>Recently Updated Records</h2>
  </div>
  <div class="record-list">${recentRecords || emptyState("No records captured yet.")}</div>
</section>`;
}

function renderCategoryPage(model: SiteModel, category: Category): string {
  const records = [...model.records[category.type]].sort(compareRecords);
  const cards = records.map((record) => recordCard(record, category.fileName, model)).join("\n");

  return `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">${escapeHtml(labelForType(category.type))}</p>
    <h2>${records.length} ${records.length === 1 ? "record" : "records"}</h2>
  </div>
  <div class="record-list">${cards || emptyState(`No ${category.title.toLowerCase()} captured yet.`)}</div>
</section>`;
}

function renderSearchPage(): string {
  return `<section class="section">
  <div class="search-panel">
    <label>
      <span>Search this wiki</span>
      <input type="search" placeholder="Type a concept, file, tag, or decision" data-search-page-input autofocus>
    </label>
  </div>
  <div class="search-results" data-search-results></div>
</section>`;
}

function renderRecordPage(record: AnyRecord, model: SiteModel, currentFile: string): string {
  const context: RenderContext = { currentFile, hrefById: model.hrefById };
  const category = categoryByType.get(record.type);
  const backHref = category ? hrefFrom(currentFile, category.fileName) : hrefFrom(currentFile, "index.html");

  return `<article class="record-page">
  <nav class="breadcrumbs" aria-label="Breadcrumb">
    <a href="${hrefFrom(currentFile, "index.html")}">Home</a>
    <span>/</span>
    <a href="${backHref}">${escapeHtml(category?.title ?? labelForType(record.type))}</a>
  </nav>
  <div class="record-title-row">
    <span class="type-badge">${escapeHtml(labelForType(record.type))}</span>
    ${tagList(recordTags(record))}
  </div>
  ${renderRecordBody(record, context)}
  ${renderRecordMeta(record, currentFile)}
</article>`;
}

function renderRecordBody(record: AnyRecord, context: RenderContext): string {
  if (record.type === "concept") {
    const details = record.details ? `<h2>Details</h2>${formatText(record.details, context)}` : "";
    return `<section class="prose">
  <h2>Summary</h2>
  ${formatText(record.summary, context)}
  ${details}
</section>`;
  }

  if (record.type === "decision") {
    return `<section class="prose">
  <h2>Context</h2>
  ${formatText(record.context || "Not recorded.", context)}
  <h2>Decision</h2>
  ${formatText(record.decision, context)}
  <h2>Consequences</h2>
  ${formatText(record.consequences || "Not recorded.", context)}
</section>`;
  }

  if (record.type === "event") {
    return `<section class="prose">
  <h2>What happened</h2>
  ${formatText(record.details || "No details recorded.", context)}
</section>`;
  }

  if (record.type === "note") {
    return `<section class="prose">
  <h2>Note</h2>
  ${formatText(record.body, context)}
</section>`;
  }

  if (record.type === "symbol") {
    return `<section class="prose">
  <h2>Purpose</h2>
  ${formatText(record.summary || "No summary recorded.", context)}
  <h2>Location</h2>
  <p>${sourceFileLink(record.file, context.currentFile)}</p>
</section>`;
  }

  return `<section class="prose">
  <h2>Relationship</h2>
  <p><strong>From:</strong> ${endpointLink(record.from, context)}</p>
  <p><strong>To:</strong> ${endpointLink(record.to, context)}</p>
  <p><strong>Relationship:</strong> ${escapeHtml(record.relationship)}</p>
</section>`;
}

function renderRecordMeta(record: AnyRecord, currentFile: string): string {
  const files = relatedFiles(record);
  const fileList = files.length
    ? files.map((file) => `<li>${sourceFileLink(file, currentFile)}</li>`).join("\n")
    : "<li>None</li>";
  const tags = recordTags(record);
  const tagText = tags.length ? tags.map((tag) => `<code>${escapeHtml(tag)}</code>`).join(" ") : "None";

  return `<details class="record-meta">
  <summary>Record details</summary>
  <dl>
    <div><dt>ID</dt><dd><code>${escapeHtml(record.id)}</code></dd></div>
    <div><dt>Source</dt><dd>${escapeHtml(record.source)}</dd></div>
    <div><dt>Authority</dt><dd>${escapeHtml(record.authority)}</dd></div>
    <div><dt>Confidence</dt><dd>${escapeHtml(record.confidence)}</dd></div>
    <div><dt>Created</dt><dd><time datetime="${escapeHtml(record.created_at)}">${escapeHtml(formatDate(record.created_at))}</time></dd></div>
    ${"updated_at" in record && typeof record.updated_at === "string" ? `<div><dt>Updated</dt><dd><time datetime="${escapeHtml(record.updated_at)}">${escapeHtml(formatDate(record.updated_at))}</time></dd></div>` : ""}
    <div><dt>Tags</dt><dd>${tagText}</dd></div>
    <div><dt>Files</dt><dd><ul>${fileList}</ul></dd></div>
  </dl>
</details>`;
}

function sectionCard(currentFile: string, targetFile: string, title: string, description: string, count: number): string {
  return `<a class="section-card" href="${hrefFrom(currentFile, targetFile)}">
  <span>${count} ${count === 1 ? "record" : "records"}</span>
  <strong>${escapeHtml(title)}</strong>
  <p>${escapeHtml(description)}</p>
</a>`;
}

function recordCard(record: AnyRecord, currentFile: string, model: SiteModel): string {
  const summary = recordSummary(record);
  const tags = recordTags(record).slice(0, 5);

  return `<article class="record-card" data-search-card>
  <div class="record-card-top">
    <span class="type-badge">${escapeHtml(labelForType(record.type))}</span>
    <span class="confidence ${escapeHtml(record.confidence)}">${escapeHtml(record.confidence)}</span>
  </div>
  <h3><a href="${hrefFrom(currentFile, recordHref(record))}">${escapeHtml(recordTitle(record))}</a></h3>
  <p>${escapeHtml(summary)}</p>
  <footer>
    ${tagList(tags)}
    <code>${escapeHtml(record.id)}</code>
  </footer>
</article>`;
}

function formatText(text: string, context: RenderContext): string {
  const trimmed = text.trim();
  if (!trimmed) {
    return "<p>Not recorded.</p>";
  }

  const blocks = trimmed.split(/\n{2,}/);
  return blocks.map((block) => formatBlock(block, context)).join("\n");
}

function formatBlock(block: string, context: RenderContext): string {
  const lines = block.split(/\r?\n/);
  if (lines.every((line) => line.trim().startsWith("- "))) {
    const items = lines
      .map((line) => `<li>${formatInline(line.trim().slice(2), context)}</li>`)
      .join("\n");
    return `<ul>${items}</ul>`;
  }

  return `<p>${formatInline(lines.join(" "), context)}</p>`;
}

function formatInline(text: string, context: RenderContext): string {
  const parts: string[] = [];
  const pattern = /(`[^`]+`|\[[^\]]+\]\([^)]+\))/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(text)) !== null) {
    parts.push(escapeHtml(text.slice(lastIndex, match.index)));
    const token = match[0];
    if (token.startsWith("`")) {
      parts.push(`<code>${escapeHtml(token.slice(1, -1))}</code>`);
    } else {
      const linkMatch = /^\[([^\]]+)\]\(([^)]+)\)$/.exec(token);
      if (linkMatch) {
        const label = linkMatch[1];
        const target = linkMatch[2];
        parts.push(`<a href="${escapeAttribute(normalizeContentHref(target, context))}">${escapeHtml(label)}</a>`);
      }
    }
    lastIndex = match.index + token.length;
  }

  parts.push(escapeHtml(text.slice(lastIndex)));
  return parts.join("");
}

function endpointLink(endpoint: string, context: RenderContext): string {
  const recordHrefForEndpoint = context.hrefById.get(endpoint);
  if (recordHrefForEndpoint) {
    return `<a href="${hrefFrom(context.currentFile, recordHrefForEndpoint)}"><code>${escapeHtml(endpoint)}</code></a>`;
  }

  const siteHref = siteHrefForTarget(endpoint, context);
  if (siteHref) {
    return `<a href="${escapeAttribute(siteHref)}"><code>${escapeHtml(endpoint)}</code></a>`;
  }

  const sourceHref = sourceHrefForFile(endpoint, context.currentFile);
  if (sourceHref) {
    return `<a class="source-link" href="${escapeAttribute(sourceHref)}"><code>${escapeHtml(endpoint)}</code></a>`;
  }

  return `<code>${escapeHtml(endpoint)}</code>`;
}

function sourceFileLink(file: string, currentFile: string): string {
  const href = sourceHrefForFile(file, currentFile);
  if (!href) {
    return `<code>${escapeHtml(file)}</code>`;
  }

  return `<a class="source-link" href="${escapeAttribute(href)}"><code>${escapeHtml(file)}</code></a>`;
}

function normalizeContentHref(target: string, context: RenderContext): string {
  const trimmed = target.trim();
  if (/^[a-z][a-z0-9+.-]*:/i.test(trimmed) || trimmed.startsWith("#")) {
    return trimmed;
  }

  const recordHrefForTarget = context.hrefById.get(trimmed);
  if (recordHrefForTarget) {
    return hrefFrom(context.currentFile, recordHrefForTarget);
  }

  const siteHref = siteHrefForTarget(trimmed, context);
  if (siteHref) {
    return siteHref;
  }

  const sourceHref = sourceHrefForFile(trimmed.replace(/^\.\//, ""), context.currentFile);
  if (sourceHref) {
    return sourceHref;
  }

  return trimmed;
}

function siteHrefForTarget(target: string, context: RenderContext): string | undefined {
  const trimmed = target.trim();
  const [withoutHash, hash = ""] = trimmed.split("#", 2);
  const hashSuffix = hash ? `#${hash}` : "";
  const normalized = withoutHash
    .replace(/\\/g, "/")
    .replace(/^\.\//, "")
    .replace(/^(\.\.\/)+/, "")
    .replace(/^wiki\//, "");
  const route = normalized.replace(/\/$/, "");
  const targetFile = markdownRouteToHtml(route);

  if (targetFile) {
    return `${hrefFrom(context.currentFile, targetFile)}${hashSuffix}`;
  }

  return undefined;
}

function markdownRouteToHtml(route: string): string | undefined {
  const routes = new Map<string, string>([
    ["", "index.html"],
    ["index", "index.html"],
    ["index.md", "index.html"],
    ["concepts", "concepts.html"],
    ["concepts.md", "concepts.html"],
    ["decisions", "decisions.html"],
    ["decisions.md", "decisions.html"],
    ["devlog", "devlog.html"],
    ["devlog.md", "devlog.html"],
    ["notes", "notes.html"],
    ["notes.md", "notes.html"],
    ["symbols", "symbols.html"],
    ["symbols.md", "symbols.html"],
    ["links", "links.html"],
    ["links.md", "links.html"]
  ]);

  return routes.get(route);
}

function sourceHrefForFile(file: string, currentFile: string): string | undefined {
  if (!file || path.isAbsolute(file) || file.startsWith("..") || file.includes("://") || file.startsWith("#")) {
    return undefined;
  }

  return `${"../".repeat(depthOf(currentFile) + 1)}${encodeURI(toPosixPath(file))}`;
}

function searchIndexJs(model: SiteModel): string {
  const entries: SearchEntry[] = model.flatRecords.map((record) => ({
    type: record.type,
    id: record.id,
    title: recordTitle(record),
    summary: recordSummary(record),
    tags: recordTags(record),
    authority: record.authority,
    confidence: record.confidence,
    url: recordHref(record),
    text: recordSearchText(record)
  }));

  return `/* Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run \`wk site\`. */
window.WIKIWIKI_SEARCH_INDEX = ${JSON.stringify(entries, null, 2)};
`;
}

function siteManifest(model: SiteModel) {
  return {
    generator: "Wikiwiki",
    generated_from: ".wikiwiki/records",
    command: "wk site",
    pages: siteStaticPageFileNames,
    records: model.flatRecords.map((record) => ({
      type: record.type,
      id: record.id,
      title: recordTitle(record),
      url: recordHref(record)
    }))
  };
}

function recordHref(record: AnyRecord): string {
  return `records/${record.type}/${safeFileName(record.id)}.html`;
}

function recordTitle(record: AnyRecord): string {
  if ("name" in record && typeof record.name === "string") {
    return record.name;
  }
  if ("title" in record && typeof record.title === "string") {
    return record.title;
  }
  if ("summary" in record && typeof record.summary === "string") {
    return record.summary;
  }
  if ("body" in record && typeof record.body === "string") {
    return record.body.slice(0, 80);
  }
  if ("relationship" in record && typeof record.relationship === "string") {
    return `${record.from} ${record.relationship} ${record.to}`;
  }
  return record.id;
}

function recordSummary(record: AnyRecord): string {
  if ("summary" in record && typeof record.summary === "string" && record.summary.trim()) {
    return record.summary.trim();
  }
  if ("decision" in record && typeof record.decision === "string" && record.decision.trim()) {
    return record.decision.trim();
  }
  if ("body" in record && typeof record.body === "string" && record.body.trim()) {
    return record.body.trim();
  }
  if ("relationship" in record && typeof record.relationship === "string") {
    return `${record.from} ${record.relationship} ${record.to}`;
  }
  return "No summary recorded.";
}

function recordSearchText(record: AnyRecord): string {
  return Object.values(record)
    .flatMap((value) => Array.isArray(value) ? value : [value])
    .filter((value): value is string => typeof value === "string")
    .join(" ");
}

function recordTimestamp(record: AnyRecord): string {
  if ("updated_at" in record && typeof record.updated_at === "string") {
    return record.updated_at;
  }

  return record.created_at;
}

function recordTags(record: AnyRecord): string[] {
  if ("tags" in record && Array.isArray(record.tags)) {
    return record.tags;
  }

  return [];
}

function relatedFiles(record: AnyRecord): string[] {
  if ("files" in record && Array.isArray(record.files)) {
    return record.files;
  }

  if ("file" in record && typeof record.file === "string") {
    return [record.file];
  }

  return [];
}

function compareRecords(a: AnyRecord, b: AnyRecord): number {
  return a.type.localeCompare(b.type) ||
    recordTitle(a).localeCompare(recordTitle(b)) ||
    a.id.localeCompare(b.id);
}

function tagList(tags: string[]): string {
  if (tags.length === 0) {
    return "";
  }

  return `<span class="tag-list">${tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join("")}</span>`;
}

function emptyState(message: string): string {
  return `<div class="empty-state">${escapeHtml(message)}</div>`;
}

function labelForType(type: RecordType): string {
  if (type === "event") {
    return "Devlog";
  }

  return type[0].toUpperCase() + type.slice(1);
}

function formatDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toISOString().slice(0, 10);
}

function hrefFrom(currentFile: string, targetFile: string): string {
  const currentDir = path.posix.dirname(currentFile);
  const relative = currentDir === "."
    ? targetFile
    : path.posix.relative(currentDir, targetFile);
  return escapeAttribute(relative || path.posix.basename(targetFile));
}

function relativePrefix(fileName: string): string {
  return "../".repeat(depthOf(fileName));
}

function depthOf(fileName: string): number {
  return fileName.split("/").length - 1;
}

function safeFileName(value: string): string {
  return value.replace(/[^a-z0-9._-]+/gi, "-");
}

function toPosixPath(value: string): string {
  return value.replace(/\\/g, "/");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value);
}

function siteCss(): string {
  return `/* Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run \`wk site\`. */
:root {
  color-scheme: light;
  --bg: #f7f7f4;
  --panel: #ffffff;
  --panel-soft: #f0f2ed;
  --text: #242521;
  --muted: #63675e;
  --border: #dcdfd6;
  --accent: #246b62;
  --accent-strong: #163f3a;
  --pink: #c43f7d;
  --code-bg: #eceee8;
  --shadow: 0 18px 45px rgba(35, 38, 31, 0.08);
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.55;
}

a {
  color: var(--accent);
  text-decoration-thickness: 0.08em;
  text-underline-offset: 0.18em;
}

code {
  border-radius: 5px;
  background: var(--code-bg);
  padding: 0.12rem 0.32rem;
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
  font-size: 0.9em;
}

.skip-link {
  position: absolute;
  left: 1rem;
  top: -4rem;
  z-index: 10;
  border-radius: 6px;
  background: var(--text);
  color: white;
  padding: 0.55rem 0.8rem;
}

.skip-link:focus {
  top: 1rem;
}

.site-shell {
  display: grid;
  grid-template-columns: 280px minmax(0, 1fr);
  min-height: 100vh;
}

.sidebar {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
  border-right: 1px solid var(--border);
  background: rgba(255, 255, 255, 0.82);
  padding: 1.1rem;
}

.brand {
  display: flex;
  align-items: center;
  gap: 0.7rem;
  color: var(--text);
  text-decoration: none;
}

.brand-mark {
  display: grid;
  place-items: center;
  width: 2.4rem;
  height: 2.4rem;
  border-radius: 50%;
  background: radial-gradient(circle at 35% 30%, #fbe8f2, #20211f 56%, #0f1110);
  color: white;
  font-weight: 800;
  letter-spacing: 0;
}

.brand strong,
.brand small {
  display: block;
}

.brand small,
.sidebar-search span,
.nav-heading,
.eyebrow {
  color: var(--muted);
  font-size: 0.76rem;
  font-weight: 700;
  letter-spacing: 0;
  text-transform: uppercase;
}

.sidebar-search {
  display: grid;
  gap: 0.35rem;
  margin: 1.2rem 0;
}

input[type="search"] {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: 7px;
  background: var(--panel);
  color: var(--text);
  padding: 0.7rem 0.78rem;
  font: inherit;
}

input[type="search"]:focus {
  border-color: var(--accent);
  outline: 3px solid rgba(36, 107, 98, 0.16);
}

.nav {
  display: grid;
  gap: 0.2rem;
}

.nav-heading {
  margin: 1rem 0 0.25rem;
}

.nav-link {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.7rem;
  border-radius: 7px;
  color: var(--text);
  padding: 0.5rem 0.58rem;
  text-decoration: none;
}

.nav-link:hover,
.nav-link.active {
  background: var(--panel-soft);
  color: var(--accent-strong);
}

.nav-link span {
  min-width: 1.7rem;
  border: 1px solid var(--border);
  border-radius: 999px;
  color: var(--muted);
  padding: 0.02rem 0.45rem;
  text-align: center;
  font-size: 0.76rem;
}

.content {
  width: min(100%, 1120px);
  padding: 2.3rem clamp(1rem, 4vw, 4rem) 4rem;
}

.page-header {
  margin-bottom: 1.5rem;
}

.page-header h1 {
  margin: 0.15rem 0 0.45rem;
  font-size: clamp(2rem, 4vw, 3.8rem);
  line-height: 1;
}

.page-header p {
  max-width: 760px;
  color: var(--muted);
  font-size: 1.08rem;
}

.hero-panel {
  display: grid;
  grid-template-columns: minmax(0, 1.5fr) minmax(260px, 0.9fr);
  gap: 1rem;
  align-items: stretch;
  border: 1px solid var(--border);
  border-radius: 8px;
  background: linear-gradient(135deg, #ffffff 0%, #f4f6f0 100%);
  box-shadow: var(--shadow);
  padding: clamp(1.1rem, 3vw, 2rem);
}

.hero-panel h2,
.section-heading h2 {
  margin: 0.2rem 0 0;
  font-size: clamp(1.35rem, 2vw, 2rem);
  line-height: 1.15;
}

.hero-panel p {
  max-width: 680px;
  color: var(--muted);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.7rem;
  margin: 0;
}

.stats-grid div {
  border: 1px solid var(--border);
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.72);
  padding: 0.9rem;
}

.stats-grid dt {
  color: var(--muted);
  font-size: 0.8rem;
}

.stats-grid dd {
  margin: 0.1rem 0 0;
  font-size: 1.7rem;
  font-weight: 800;
}

.section {
  margin-top: 2rem;
}

.section-heading {
  margin-bottom: 0.9rem;
}

.card-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.85rem;
}

.card-grid.compact {
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.section-card,
.record-card,
.search-result,
.empty-state,
.search-panel,
.record-meta {
  border: 1px solid var(--border);
  border-radius: 8px;
  background: var(--panel);
}

.section-card {
  display: block;
  min-height: 9.5rem;
  color: var(--text);
  padding: 1rem;
  text-decoration: none;
}

.section-card:hover,
.record-card:hover,
.search-result:hover {
  border-color: rgba(36, 107, 98, 0.4);
  box-shadow: var(--shadow);
}

.section-card span {
  color: var(--pink);
  font-size: 0.8rem;
  font-weight: 700;
}

.section-card strong {
  display: block;
  margin: 0.35rem 0;
  font-size: 1.25rem;
}

.section-card p,
.record-card p,
.search-result p {
  margin-bottom: 0;
  color: var(--muted);
}

.record-list {
  display: grid;
  gap: 0.75rem;
}

.record-card,
.search-result {
  padding: 1rem;
}

.record-card-top,
.record-card footer,
.record-title-row,
.search-result footer {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.5rem;
}

.record-card-top {
  justify-content: space-between;
}

.record-card h3,
.search-result h3 {
  margin: 0.6rem 0 0.25rem;
  font-size: 1.15rem;
}

.record-card h3 a,
.search-result h3 a {
  color: var(--text);
}

.record-card footer,
.search-result footer {
  justify-content: space-between;
  margin-top: 0.85rem;
}

.type-badge,
.confidence,
.tag-list span {
  display: inline-flex;
  align-items: center;
  min-height: 1.45rem;
  border-radius: 999px;
  padding: 0.12rem 0.5rem;
  font-size: 0.76rem;
  font-weight: 700;
}

.type-badge {
  background: #e5f0ed;
  color: var(--accent-strong);
}

.confidence {
  background: var(--panel-soft);
  color: var(--muted);
}

.confidence.high {
  background: #e7f3df;
  color: #2d5c1f;
}

.confidence.low {
  background: #f5e7df;
  color: #7a3c1d;
}

.tag-list {
  display: inline-flex;
  flex-wrap: wrap;
  gap: 0.3rem;
}

.tag-list span {
  background: #f8e8f1;
  color: #743050;
}

.record-page {
  max-width: 860px;
}

.breadcrumbs {
  display: flex;
  gap: 0.45rem;
  margin-bottom: 1rem;
  color: var(--muted);
  font-size: 0.9rem;
}

.prose {
  border: 1px solid var(--border);
  border-radius: 8px;
  background: var(--panel);
  padding: clamp(1rem, 3vw, 1.6rem);
}

.prose h2 {
  margin: 1.3rem 0 0.3rem;
  font-size: 1.25rem;
}

.prose h2:first-child {
  margin-top: 0;
}

.prose p,
.prose ul {
  color: #373933;
}

.record-meta {
  margin-top: 1rem;
  padding: 0.75rem 1rem;
}

.record-meta summary {
  cursor: pointer;
  font-weight: 700;
}

.record-meta dl {
  display: grid;
  gap: 0.55rem;
  margin: 0.8rem 0 0;
}

.record-meta dl div {
  display: grid;
  grid-template-columns: 7rem minmax(0, 1fr);
  gap: 0.75rem;
}

.record-meta dt {
  color: var(--muted);
  font-weight: 700;
}

.record-meta dd {
  margin: 0;
}

.record-meta ul {
  margin: 0;
  padding-left: 1.1rem;
}

.search-panel {
  padding: 1rem;
}

.search-panel label {
  display: grid;
  gap: 0.45rem;
  font-weight: 700;
}

.search-results {
  display: grid;
  gap: 0.75rem;
  margin-top: 1rem;
}

.empty-state {
  color: var(--muted);
  padding: 1rem;
}

@media (max-width: 860px) {
  .site-shell {
    grid-template-columns: 1fr;
  }

  .sidebar {
    position: static;
    height: auto;
    border-bottom: 1px solid var(--border);
    border-right: 0;
  }

  .nav {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .nav-heading {
    grid-column: 1 / -1;
  }

  .hero-panel,
  .card-grid,
  .card-grid.compact {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 560px) {
  .content {
    padding: 1.4rem 1rem 3rem;
  }

  .nav {
    grid-template-columns: 1fr;
  }

  .stats-grid {
    grid-template-columns: 1fr;
  }

  .record-meta dl div {
    grid-template-columns: 1fr;
    gap: 0.1rem;
  }
}
`;
}

function siteJs(): string {
  return `/* Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run \`wk site\`. */
(function () {
  const entries = Array.isArray(window.WIKIWIKI_SEARCH_INDEX) ? window.WIKIWIKI_SEARCH_INDEX : [];

  function escapeHtml(value) {
    return String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function normalize(value) {
    return String(value || "").toLowerCase();
  }

  function resultHtml(entry) {
    const tags = Array.isArray(entry.tags) && entry.tags.length
      ? '<span class="tag-list">' + entry.tags.slice(0, 6).map((tag) => '<span>' + escapeHtml(tag) + '</span>').join("") + '</span>'
      : "";
    return '<article class="search-result">' +
      '<div class="record-card-top"><span class="type-badge">' + escapeHtml(entry.type) + '</span><span class="confidence ' + escapeHtml(entry.confidence) + '">' + escapeHtml(entry.confidence) + '</span></div>' +
      '<h3><a href="' + encodeURI(entry.url) + '">' + escapeHtml(entry.title) + '</a></h3>' +
      '<p>' + escapeHtml(entry.summary) + '</p>' +
      '<footer>' + tags + '<code>' + escapeHtml(entry.id) + '</code></footer>' +
    '</article>';
  }

  function search(query) {
    const normalizedQuery = normalize(query).trim();
    if (!normalizedQuery) {
      return entries.slice(0, 20);
    }

    const terms = normalizedQuery.split(/\\s+/).filter(Boolean);
    return entries
      .map((entry) => {
        const text = normalize([entry.title, entry.summary, entry.text, entry.id, entry.type, (entry.tags || []).join(" ")].join(" "));
        const matchedTerms = terms.filter((term) => text.includes(term)).length;
        return { entry, matchedTerms };
      })
      .filter((result) => result.matchedTerms > 0)
      .sort((a, b) => b.matchedTerms - a.matchedTerms || a.entry.title.localeCompare(b.entry.title))
      .slice(0, 50)
      .map((result) => result.entry);
  }

  function updateSearchPage(query) {
    const resultsRoot = document.querySelector("[data-search-results]");
    if (!resultsRoot) {
      return;
    }

    const matches = search(query);
    resultsRoot.innerHTML = matches.length
      ? matches.map(resultHtml).join("")
      : '<div class="empty-state">No matching records.</div>';
  }

  const params = new URLSearchParams(window.location.search);
  const initialQuery = params.get("q") || "";
  const pageInput = document.querySelector("[data-search-page-input]");
  if (pageInput) {
    pageInput.value = initialQuery;
    pageInput.addEventListener("input", () => updateSearchPage(pageInput.value));
    updateSearchPage(initialQuery);
  }

  document.querySelectorAll("[data-site-search]").forEach((input) => {
    input.addEventListener("keydown", (event) => {
      if (event.key !== "Enter") {
        return;
      }
      event.preventDefault();
      const target = input.getAttribute("data-search-target") || "search.html";
      const query = input.value ? "?q=" + encodeURIComponent(input.value) : "";
      window.location.href = target + query;
    });
  });
}());
`;
}
