import fs from "fs";
import path from "path";
import { readIntegrations, shouldReportIntegrations, type BeadsIntegrationSummary, type BeadsIssueSummary, type IntegrationSummary } from "./beads";
import { normalizeSourceBaseUrl, readWikiwikiConfig, readWikiwikiSiteTheme, type WikiwikiSiteTheme } from "./config";
import { sitePath } from "./paths";
import { readAllRecords, type RecordsByType } from "./store";
import { type AnyRecord, type RecordType, recordTypes } from "./schemas";
import { audienceTags, parseSiteAudience, userMaterialTags, type SiteAudience } from "./profiles";

export const siteGeneratedNotice =
  "<!-- Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run `wk site`. -->";

export const siteStaticPageFileNames = [
  "index.html",
  "guides.html",
  "concepts.html",
  "decisions.html",
  "devlog.html",
  "notes.html",
  "symbols.html",
  "links.html",
  "work.html",
  "search.html"
] as const;

export type SiteFile = {
  fileName: string;
  content: string;
};

export type SiteOptions = {
  sourceBaseUrl?: string;
  audience?: SiteAudience;
};

export type ResolvedSiteOptions = {
  sourceBaseUrl?: string;
  theme: WikiwikiSiteTheme;
  audience: SiteAudience;
};

type Category = {
  type: RecordType;
  title: string;
  navLabel: string;
  fileName: string;
  description: string;
};

type SiteModel = {
  root: string;
  repoName: string;
  siteTitle: string;
  siteDescription: string;
  projectInitials: string;
  records: RecordsByType;
  flatRecords: AnyRecord[];
  hrefById: Map<string, string>;
  counts: Record<RecordType, number>;
  visibleCategories: Category[];
  options: ResolvedSiteOptions;
  audience: SiteAudience;
  integrations: IntegrationSummary;
};

type LayoutOptions = {
  model: SiteModel;
  fileName: string;
  title: string;
  description: string;
  active: string;
  body: string;
};

type RenderContext = {
  root: string;
  currentFile: string;
  hrefById: Map<string, string>;
  sourceBaseUrl?: string;
};

type SearchEntry = {
  type: string;
  typeLabel: string;
  id: string;
  title: string;
  summary: string;
  tags: string[];
  authority: string;
  confidence: string;
  audienceLabel: string;
  url: string;
  text: string;
};

const categories: Category[] = [
  {
    type: "concept",
    title: "Concepts",
    navLabel: "Concepts",
    fileName: "concepts.html",
    description: "Durable explanations, domain terms, product ideas, and system concepts."
  },
  {
    type: "decision",
    title: "Decisions",
    navLabel: "Decisions",
    fileName: "decisions.html",
    description: "Product, architecture, workflow, and implementation decisions with rationale."
  },
  {
    type: "event",
    title: "Devlog",
    navLabel: "Devlog",
    fileName: "devlog.html",
    description: "Meaningful changes and development milestones in chronological context."
  },
  {
    type: "note",
    title: "Notes",
    navLabel: "Notes",
    fileName: "notes.html",
    description: "Lightweight facts, reminders, and working context."
  },
  {
    type: "symbol",
    title: "Symbols",
    navLabel: "Symbols",
    fileName: "symbols.html",
    description: "Important code symbols and where maintainers should look first."
  },
  {
    type: "link",
    title: "Links",
    navLabel: "Links",
    fileName: "links.html",
    description: "Relationships between records, files, generated docs, and source concepts."
  }
];

const categoryByType = new Map<RecordType, Category>(categories.map((category) => [category.type, category]));

export function buildSiteFiles(root: string, options: SiteOptions = {}): SiteFile[] {
  const records = readAllRecords(root);
  const model = createSiteModel(root, records, resolveSiteOptions(root, options));
  const files: SiteFile[] = [];

  files.push({
    fileName: "index.html",
    content: renderLayout({
      model,
      fileName: "index.html",
      title: model.siteTitle,
      description: model.siteDescription,
      active: "home",
      body: renderHomePage(model)
    })
  });

  files.push({
    fileName: "guides.html",
    content: renderLayout({
      model,
      fileName: "guides.html",
      title: "Guides",
      description: `Curated paths through ${model.repoName} knowledge.`,
      active: "guides",
      body: renderGuidesPage(model)
    })
  });

  for (const category of categories) {
    files.push({
      fileName: category.fileName,
      content: renderLayout({
        model,
        fileName: category.fileName,
        title: category.title,
        description: category.description,
        active: category.type,
        body: renderCategoryPage(model, category)
      })
    });
  }

  if (showBeadsWork(model)) {
    files.push({
      fileName: "work.html",
      content: renderLayout({
        model,
        fileName: "work.html",
        title: "Project Work",
        description: "Developer-only Beads task context for this project.",
        active: "work",
        body: renderWorkPage(model)
      })
    });
  }

  files.push({
    fileName: "search.html",
    content: renderLayout({
      model,
      fileName: "search.html",
      title: "Search",
      description: "Search this project wiki without a backend.",
      active: "search",
      body: renderSearchPage()
    })
  });

  for (const record of model.flatRecords) {
    const fileName = recordHref(record);
    files.push({
      fileName,
      content: renderLayout({
        model,
        fileName,
        title: recordTitle(record),
        description: recordSummary(record),
        active: record.type,
        body: renderRecordPage(record, model, fileName)
      })
    });
  }

  files.push(
    { fileName: "assets/wikiwiki.css", content: siteCss() },
    { fileName: "assets/project-theme.css", content: projectThemeCss(model.options.theme) },
    { fileName: "assets/search-index.js", content: searchIndexJs(model) },
    { fileName: "assets/wikiwiki.js", content: siteJs() },
    { fileName: ".nojekyll", content: "" },
    { fileName: "site-manifest.json", content: `${JSON.stringify(siteManifest(model), null, 2)}\n` }
  );

  return files;
}

export function renderSite(root: string, options: SiteOptions = {}): string[] {
  const files = buildSiteFiles(root, options);
  const outputPath = sitePath(root);

  fs.rmSync(outputPath, { recursive: true, force: true });
  fs.mkdirSync(outputPath, { recursive: true });

  return files.map((file) => {
    const outputFile = path.join(outputPath, file.fileName);
    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
    fs.writeFileSync(outputFile, file.content, "utf8");
    return outputFile;
  });
}

export function resolveSiteOptions(root: string, options: SiteOptions = {}): ResolvedSiteOptions {
  const config = readWikiwikiConfig(root);
  return {
    sourceBaseUrl: normalizeSourceBaseUrl(options.sourceBaseUrl ?? config.source_base_url),
    theme: readWikiwikiSiteTheme(root),
    audience: parseSiteAudience(options.audience ?? config.site_audience, "all")
  };
}

function createSiteModel(root: string, records: RecordsByType, options: ResolvedSiteOptions): SiteModel {
  const audienceRecords = filterRecordsByAudience(records, options.audience);
  const integrations = readIntegrations(root, readWikiwikiConfig(root));
  const flatRecords: AnyRecord[] = [];
  for (const type of recordTypes) {
    flatRecords.push(...audienceRecords[type]);
  }
  flatRecords.sort(compareRecords);
  const hrefById = new Map(flatRecords.map((record) => [record.id, recordHref(record)]));
  const counts = Object.fromEntries(recordTypes.map((type) => [type, audienceRecords[type].length])) as Record<RecordType, number>;
  const repoName = options.theme.project_name?.trim() || path.basename(root);

  return {
    root,
    repoName,
    siteTitle: `${repoName} Wiki`,
    siteDescription: options.theme.project_description?.trim() || "A project wiki generated from durable repo knowledge.",
    projectInitials: initialsForName(repoName),
    records: audienceRecords,
    flatRecords,
    hrefById,
    counts,
    visibleCategories: categories.filter((category) => counts[category.type] > 0),
    options,
    audience: options.audience,
    integrations
  };
}

function renderLayout(options: LayoutOptions): string {
  const prefix = relativePrefix(options.fileName);
  const htmlTitle = options.title === options.model.siteTitle
    ? options.title
    : `${options.title} - ${options.model.siteTitle}`;

  return `${siteGeneratedNotice}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="Wikiwiki">
  <title>${escapeHtml(htmlTitle)}</title>
  <link rel="stylesheet" href="${prefix}assets/wikiwiki.css">
  <link rel="stylesheet" href="${prefix}assets/project-theme.css">
  <script src="${prefix}assets/search-index.js" defer></script>
  <script src="${prefix}assets/wikiwiki.js" defer></script>
</head>
<body>
  <a class="skip-link" href="#content">Skip to content</a>
  <div class="site-shell">
    <aside class="sidebar" aria-label="Wiki navigation">
      <div class="sidebar-top">
        <a class="brand" href="${hrefFrom(options.fileName, "index.html")}" aria-label="Wiki home">
          <span class="brand-mark">${escapeHtml(options.model.projectInitials)}</span>
          <span>
            <strong>${escapeHtml(options.model.repoName)}</strong>
            <small>Project wiki</small>
          </span>
        </a>
        <button class="nav-toggle" type="button" data-nav-toggle aria-expanded="false">Menu</button>
      </div>
      <div class="sidebar-nav" data-sidebar-nav>
        ${renderNav(options.model, options.fileName, options.active)}
      </div>
    </aside>
    <main id="content" class="content">
      <header class="page-header">
        <h1>${escapeHtml(options.title)}</h1>
        <p>${escapeHtml(options.description)}</p>
      </header>
      ${options.body}
      <footer class="site-footer">Created with <a href="https://github.com/Thjodann/Wikiwiki">Wikiwiki</a>.</footer>
    </main>
  </div>
</body>
</html>
`;
}

function renderNav(model: SiteModel, currentFile: string, active: string): string {
  const categoryLinks = model.visibleCategories
    .map((category) => navLink(currentFile, category.fileName, category.navLabel, active === category.type, model.counts[category.type]))
    .join("\n");
  const categorySection = categoryLinks
    ? `<p class="nav-heading">Agent records</p>\n${categoryLinks}`
    : "";
  const links = [
    `<p class="nav-heading">Start Here</p>`,
    navLink(currentFile, "index.html", "Home", active === "home"),
    navLink(currentFile, "guides.html", "Guides", active === "guides"),
    navLink(currentFile, "search.html", "Search", active === "search"),
    showBeadsWork(model) ? navLink(currentFile, "work.html", "Project Work", active === "work", beadsNavCount(model.integrations.beads)) : "",
    categorySection
  ].filter(Boolean).join("\n");

  return `<nav class="nav">
${links}
</nav>`;
}

function navLink(currentFile: string, targetFile: string, label: string, active: boolean, count?: number): string {
  const countHtml = typeof count === "number" ? `<span>${count}</span>` : "";
  const activeAttribute = active ? ` aria-current="page"` : "";
  return `<a class="nav-link${active ? " active" : ""}" href="${hrefFrom(currentFile, targetFile)}"${activeAttribute}>${escapeHtml(label)}${countHtml}</a>`;
}

function renderHomePage(model: SiteModel): string {
  const coreCategories = categories
    .filter((category) => ["concept", "decision"].includes(category.type) && model.counts[category.type] > 0);
  const supportCategories = categories
    .filter((category) => !["concept", "decision"].includes(category.type) && model.counts[category.type] > 0);
  const guideCards = [
    sectionCard("index.html", "guides.html", "Guides", "Curated paths through user orientation, project concepts, and maintainer context.")
  ].join("\n");
  const primaryCards = coreCategories
    .map((category) => sectionCard("index.html", category.fileName, category.title, category.description, model.counts[category.type]))
    .join("\n");
  const supportCards = supportCategories
    .map((category) => sectionCard("index.html", category.fileName, category.title, category.description, model.counts[category.type]))
    .join("\n");
  const workCards = showBeadsWork(model)
    ? sectionCard("index.html", "work.html", "Project Work", "Developer-only Beads task context: ready work, in-progress issues, and recent closed work.", beadsNavCount(model.integrations.beads))
    : "";
  const featuredRecords = homepageRecords(model)
    .map((record) => recordCard(record, "index.html", model))
    .join("\n");
  const stats = statsTypes(model)
    .map((type) => `<div><dt>${escapeHtml(labelForType(type))}</dt><dd>${model.counts[type]}</dd></div>`)
    .join("\n");

  return `<section class="hero-panel">
  <div>
    <p class="eyebrow">Start here</p>
    <h2>Understand ${escapeHtml(model.repoName)} without reading raw records.</h2>
    <p>${escapeHtml(model.siteDescription)} ${escapeHtml(audienceIntro(model.audience))}</p>
  </div>
  ${stats ? `<dl class="stats-grid">${stats}</dl>` : ""}
</section>

<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Field guide</p>
    <h2>Start with the project story</h2>
  </div>
  <div class="card-grid">${guideCards}${primaryCards}</div>
</section>

${workCards || supportCards ? `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Maintainer context</p>
    <h2>Browse the source records</h2>
  </div>
  <div class="card-grid compact">${workCards}${supportCards}</div>
</section>` : ""}

<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Featured</p>
    <h2>High-signal knowledge</h2>
  </div>
  <div class="record-list">${featuredRecords || emptyState("No curated records yet. Add high-confidence concepts or decisions to shape this front page.")}</div>
</section>`;
}

function renderGuidesPage(model: SiteModel): string {
  const usedRecords = new Set<string>();
  const userGuideRecords = takeUnusedRecords(userGuideRecordsFor(model), usedRecords, 8);
  const startHereRecords = takeUnusedRecords(homepageRecords(model), usedRecords, 6);
  const conceptRecords = takeUnusedRecords(curatedRecords(model, ["concept"], model.records.concept.length), usedRecords, 6);
  const decisionRecords = takeUnusedRecords(curatedRecords(model, ["decision"], model.records.decision.length), usedRecords, 6);
  const userGuideCards = userGuideRecords
    .map((record) => recordCard(record, "guides.html", model))
    .join("\n");
  const userGuideSection = userGuideCards ? `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">User guide</p>
    <h2>Start, learn, and troubleshoot</h2>
  </div>
  <div class="record-list">${userGuideCards}</div>
</section>

` : "";
  const startHere = startHereRecords
    .map((record) => recordCard(record, "guides.html", model))
    .join("\n");
  const conceptCards = conceptRecords
    .map((record) => recordCard(record, "guides.html", model))
    .join("\n");
  const decisionCards = decisionRecords
    .map((record) => recordCard(record, "guides.html", model))
    .join("\n");
  const maintainerCards = categories
    .filter((category) => model.counts[category.type] > 0)
    .map((category) => sectionCard("guides.html", category.fileName, category.title, category.description, model.counts[category.type]))
    .join("\n");
  const workCard = showBeadsWork(model)
    ? sectionCard("guides.html", "work.html", "Project Work", "Developer-only Beads task context for planning, blockers, and completed work.", beadsNavCount(model.integrations.beads))
    : "";

  return `${userGuideSection}<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Start here</p>
    <h2>Project essentials</h2>
  </div>
  <div class="record-list">${startHere || emptyState("No high-signal records captured yet.")}</div>
</section>

${conceptCards ? `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Experience</p>
    <h2>Concepts to understand first</h2>
  </div>
  <div class="record-list">${conceptCards}</div>
</section>` : ""}

${decisionCards ? `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Rationale</p>
    <h2>Decisions that shaped the project</h2>
  </div>
  <div class="record-list">${decisionCards}</div>
</section>` : ""}

${workCard || maintainerCards ? `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Docs map</p>
    <h2>Agent-maintained record indexes</h2>
  </div>
  <div class="card-grid compact">${workCard}${maintainerCards}</div>
</section>` : ""}`;
}

function renderWorkPage(model: SiteModel): string {
  const beads = model.integrations.beads;
  if (!beads) {
    return `<section class="section">${emptyState("No Beads workspace detected.")}</section>`;
  }

  if (!beads.enabled) {
    return `<section class="section">${emptyState("Beads is detected but disabled in Wikiwiki config.")}</section>`;
  }

  if (!beads.available) {
    return `<section class="section">
  <div class="empty-state">
    <strong>Beads workspace detected.</strong>
    <p>Wikiwiki could not read Beads with <code>bd --readonly --json</code>. ${escapeHtml(beads.error ?? "Install bd or check the Beads workspace, then rerun wk site.")}</p>
  </div>
</section>`;
  }

  const stats = [
    ["Ready", beads.counts.ready],
    ["In progress", beads.counts.in_progress],
    ["Recent closed", beads.counts.recent_closed],
    ["Total", beads.counts.total]
  ]
    .filter(([, value]) => typeof value === "number")
    .map(([label, value]) => `<div><dt>${escapeHtml(String(label))}</dt><dd>${value}</dd></div>`)
    .join("\n");

  return `<section class="hero-panel">
  <div>
    <p class="eyebrow">Developer work graph</p>
    <h2>Beads tracks what to do; Wikiwiki records what becomes true.</h2>
    <p>Use this page to orient on active task context without turning tasks into wiki records.</p>
  </div>
  ${stats ? `<dl class="stats-grid">${stats}</dl>` : ""}
</section>

${beadsIssueSection("Ready work", "Open work with no active blockers.", beads.ready)}
${beadsIssueSection("In progress", "Work currently claimed or underway.", beads.in_progress)}
${beadsIssueSection("Recently closed", "Completed work that may have durable wiki outcomes.", beads.recent_closed)}`;
}

function beadsIssueSection(title: string, description: string, issues: BeadsIssueSummary[]): string {
  const cards = issues.map(beadsIssueCard).join("\n");
  return `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">Beads</p>
    <h2>${escapeHtml(title)}</h2>
    <p>${escapeHtml(description)}</p>
  </div>
  <div class="record-list">${cards || emptyState(`No ${title.toLowerCase()} found.`)}</div>
</section>`;
}

function beadsIssueCard(issue: BeadsIssueSummary): string {
  const details = [
    issue.type,
    issue.status,
    issue.priority,
    issue.assignee ? `Assigned to ${issue.assignee}` : ""
  ].filter(Boolean).join(" · ");
  const labels = issue.labels.length > 0 ? tagList(issue.labels.slice(0, 6)) : "";
  return `<article class="record-card work-card">
  <div class="record-card-top">
    <span class="type-badge">Beads</span>
    <code>${escapeHtml(issue.id)}</code>
  </div>
  <h3>${escapeHtml(issue.title)}</h3>
  ${details ? `<p>${escapeHtml(details)}</p>` : ""}
  ${labels ? `<footer>${labels}</footer>` : ""}
</article>`;
}

function renderCategoryPage(model: SiteModel, category: Category): string {
  const records = [...model.records[category.type]].sort(compareRecords);
  const cards = records.map((record) => recordCard(record, category.fileName, model)).join("\n");

  return `<section class="section">
  <div class="section-heading">
    <p class="eyebrow">${escapeHtml(labelForType(category.type))}</p>
    <h2>${records.length} ${records.length === 1 ? "record" : "records"}</h2>
  </div>
  <div class="record-list">${cards || emptyState(`No ${category.title.toLowerCase()} captured yet.`)}</div>
</section>`;
}

function renderSearchPage(): string {
  return `<section class="section">
  <div class="search-panel">
    <label>
      <span>Search this project wiki</span>
      <input type="search" placeholder="Type a concept, file, tag, or decision" data-search-page-input autofocus>
    </label>
  </div>
  <div class="search-results" data-search-results></div>
</section>`;
}

function renderRecordPage(record: AnyRecord, model: SiteModel, currentFile: string): string {
  const context: RenderContext = {
    root: model.root,
    currentFile,
    hrefById: model.hrefById,
    sourceBaseUrl: model.options.sourceBaseUrl
  };
  const category = categoryByType.get(record.type);
  const backHref = category ? hrefFrom(currentFile, category.fileName) : hrefFrom(currentFile, "index.html");
  const tagsHtml = tagList(displayTags(record));
  const tagsLine = tagsHtml ? `\n    ${tagsHtml}` : "";
  const sourcesBlock = renderSourcesBlock(record, context);
  const audienceHtml = audienceLabel(record)
    ? `<span class="audience-badge">${escapeHtml(audienceLabel(record))}</span>`
    : "";

  return `<article class="record-page">
  <nav class="breadcrumbs" aria-label="Breadcrumb">
    <a href="${hrefFrom(currentFile, "index.html")}">Home</a>
    <span>/</span>
    <a href="${backHref}">${escapeHtml(category?.title ?? labelForType(record.type))}</a>
  </nav>
  <div class="record-title-row">
    <span class="type-badge">${escapeHtml(labelForType(record.type))}</span>${audienceHtml}${tagsLine}
  </div>
  ${renderRecordBody(record, context)}${sourcesBlock ? `\n  ${sourcesBlock}` : ""}
  ${renderRecordMeta(record, context)}
</article>`;
}

function renderRecordBody(record: AnyRecord, context: RenderContext): string {
  if (record.type === "concept") {
    const details = record.details ? `<h2>Details</h2>${formatText(record.details, context)}` : "";
    return `<section class="prose">
  <h2>Summary</h2>
  ${formatText(record.summary, context)}
  ${details}
</section>`;
  }

  if (record.type === "decision") {
    return `<section class="prose">
  <h2>Context</h2>
  ${formatText(record.context || "Not recorded.", context)}
  <h2>Decision</h2>
  ${formatText(record.decision, context)}
  <h2>Consequences</h2>
  ${formatText(record.consequences || "Not recorded.", context)}
</section>`;
  }

  if (record.type === "event") {
    return `<section class="prose">
  <h2>What happened</h2>
  ${formatText(record.details || "No details recorded.", context)}
</section>`;
  }

  if (record.type === "note") {
    return `<section class="prose">
  <h2>Note</h2>
  ${formatText(record.body, context)}
</section>`;
  }

  if (record.type === "symbol") {
    return `<section class="prose">
  <h2>Purpose</h2>
  ${formatText(record.summary || "No summary recorded.", context)}
  <h2>Location</h2>
  <p>${sourceFileLink(record.file, context)}</p>
</section>`;
  }

  return `<section class="prose">
  <h2>Relationship</h2>
  <p><strong>From:</strong> ${endpointLink(record.from, context)}</p>
  <p><strong>To:</strong> ${endpointLink(record.to, context)}</p>
  <p><strong>Relationship:</strong> ${escapeHtml(record.relationship)}</p>
</section>`;
}

function renderRecordMeta(record: AnyRecord, context: RenderContext): string {
  const files = relatedFiles(record);
  const fileList = files.length
    ? files.map((file) => `<li>${sourceFileLink(file, context)}</li>`).join("\n")
    : "<li>None</li>";
  const tags = recordTags(record);
  const tagText = tags.length ? tags.map((tag) => `<code>${escapeHtml(tag)}</code>`).join(" ") : "None";
  const updatedAt = "updated_at" in record && typeof record.updated_at === "string"
    ? `\n    <div><dt>Updated</dt><dd><time datetime="${escapeHtml(record.updated_at)}">${escapeHtml(formatDate(record.updated_at))}</time></dd></div>`
    : "";

  return `<details class="record-meta">
  <summary>Agent details</summary>
  <dl>
    <div><dt>ID</dt><dd><code>${escapeHtml(record.id)}</code></dd></div>
    <div><dt>Source</dt><dd>${escapeHtml(record.source)}</dd></div>
    <div><dt>Authority</dt><dd>${escapeHtml(record.authority)}</dd></div>
    <div><dt>Confidence</dt><dd>${escapeHtml(record.confidence)}</dd></div>
    <div><dt>Created</dt><dd><time datetime="${escapeHtml(record.created_at)}">${escapeHtml(formatDate(record.created_at))}</time></dd></div>${updatedAt}
    <div><dt>Tags</dt><dd>${tagText}</dd></div>
    <div><dt>Files</dt><dd><ul>${fileList}</ul></dd></div>
  </dl>
</details>`;
}

function renderSourcesBlock(record: AnyRecord, context: RenderContext): string {
  const files = relatedFiles(record);
  if (files.length === 0) {
    return "";
  }

  const fileList = files.map((file) => `<li>${sourceFileLink(file, context)}</li>`).join("\n");
  return `<aside class="sources-panel">
  <h2>Related files</h2>
  <ul>${fileList}</ul>
</aside>`;
}

function sectionCard(currentFile: string, targetFile: string, title: string, description: string, count?: number): string {
  const countHtml = typeof count === "number"
    ? `<span>${count} ${count === 1 ? "record" : "records"}</span>`
    : "<span>Guide</span>";
  return `<a class="section-card" href="${hrefFrom(currentFile, targetFile)}">
  ${countHtml}
  <strong>${escapeHtml(title)}</strong>
  <p>${escapeHtml(description)}</p>
</a>`;
}

function recordCard(record: AnyRecord, currentFile: string, _model: SiteModel): string {
  const summary = recordExcerpt(record);
  const tags = displayTags(record).slice(0, 5);
  const tagsHtml = tagList(tags);
  const tagsLine = tagsHtml ? `\n    ${tagsHtml}` : "";
  const audienceHtml = audienceLabel(record)
    ? `<span class="audience-badge">${escapeHtml(audienceLabel(record))}</span>`
    : "";

  return `<article class="record-card" data-search-card>
  <div class="record-card-top">
    <span class="type-badge">${escapeHtml(labelForType(record.type))}</span>${audienceHtml}
  </div>
  <h3><a href="${hrefFrom(currentFile, recordHref(record))}">${escapeHtml(recordTitle(record))}</a></h3>
  <p>${escapeHtml(summary)}</p>${tagsLine ? `\n  <footer>${tagsLine}</footer>` : ""}
</article>`;
}

function formatText(text: string, context: RenderContext): string {
  const trimmed = text.trim();
  if (!trimmed) {
    return "<p>Not recorded.</p>";
  }

  const blocks = trimmed.split(/\n{2,}/);
  return blocks.map((block) => formatBlock(block, context)).join("\n");
}

function formatBlock(block: string, context: RenderContext): string {
  const lines = block.split(/\r?\n/);
  if (lines.every((line) => line.trim().startsWith("- "))) {
    const items = lines
      .map((line) => `<li>${formatInline(line.trim().slice(2), context)}</li>`)
      .join("\n");
    return `<ul>${items}</ul>`;
  }

  return `<p>${formatInline(lines.join(" "), context)}</p>`;
}

function formatInline(text: string, context: RenderContext): string {
  const parts: string[] = [];
  const pattern = /(`[^`]+`|\[[^\]]+\]\([^)]+\))/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(text)) !== null) {
    parts.push(escapeHtml(text.slice(lastIndex, match.index)));
    const token = match[0];
    if (token.startsWith("`")) {
      parts.push(`<code>${escapeHtml(token.slice(1, -1))}</code>`);
    } else {
      const linkMatch = /^\[([^\]]+)\]\(([^)]+)\)$/.exec(token);
      if (linkMatch) {
        const label = linkMatch[1];
        const target = linkMatch[2];
        parts.push(`<a href="${escapeAttribute(normalizeContentHref(target, context))}">${escapeHtml(label)}</a>`);
      }
    }
    lastIndex = match.index + token.length;
  }

  parts.push(escapeHtml(text.slice(lastIndex)));
  return parts.join("");
}

function endpointLink(endpoint: string, context: RenderContext): string {
  const recordHrefForEndpoint = context.hrefById.get(endpoint);
  if (recordHrefForEndpoint) {
    return `<a href="${hrefFrom(context.currentFile, recordHrefForEndpoint)}"><code>${escapeHtml(endpoint)}</code></a>`;
  }

  const siteHref = siteHrefForTarget(endpoint, context);
  if (siteHref) {
    return `<a href="${escapeAttribute(siteHref)}"><code>${escapeHtml(endpoint)}</code></a>`;
  }

  const sourceHref = sourceHrefForFile(endpoint, context);
  if (sourceHref) {
    return `<a class="source-link" href="${escapeAttribute(sourceHref)}"><code>${escapeHtml(endpoint)}</code></a>`;
  }

  return `<code>${escapeHtml(endpoint)}</code>`;
}

function sourceFileLink(file: string, context: RenderContext): string {
  const href = sourceHrefForFile(file, context);
  if (!href) {
    return `<code>${escapeHtml(file)}</code>`;
  }

  return `<a class="source-link" href="${escapeAttribute(href)}"><code>${escapeHtml(file)}</code></a>`;
}

function normalizeContentHref(target: string, context: RenderContext): string {
  const trimmed = target.trim();
  if (/^[a-z][a-z0-9+.-]*:/i.test(trimmed) || trimmed.startsWith("#")) {
    return trimmed;
  }

  const recordHrefForTarget = context.hrefById.get(trimmed);
  if (recordHrefForTarget) {
    return hrefFrom(context.currentFile, recordHrefForTarget);
  }

  const siteHref = siteHrefForTarget(trimmed, context);
  if (siteHref) {
    return siteHref;
  }

  const sourceHref = sourceHrefForFile(trimmed.replace(/^\.\//, ""), context);
  if (sourceHref) {
    return sourceHref;
  }

  return trimmed;
}

function siteHrefForTarget(target: string, context: RenderContext): string | undefined {
  const trimmed = target.trim();
  const [withoutHash, hash = ""] = trimmed.split("#", 2);
  const hashSuffix = hash ? `#${hash}` : "";
  const normalized = withoutHash
    .replace(/\\/g, "/")
    .replace(/^\.\//, "")
    .replace(/^(\.\.\/)+/, "")
    .replace(/^wiki\//, "");
  const route = normalized.replace(/\/$/, "");
  const targetFile = markdownRouteToHtml(route);

  if (targetFile) {
    return `${hrefFrom(context.currentFile, targetFile)}${hashSuffix}`;
  }

  return undefined;
}

function markdownRouteToHtml(route: string): string | undefined {
  const routes = new Map<string, string>([
    ["", "index.html"],
    ["index", "index.html"],
    ["index.md", "index.html"],
    ["guides", "guides.html"],
    ["guides.md", "guides.html"],
    ["concepts", "concepts.html"],
    ["concepts.md", "concepts.html"],
    ["decisions", "decisions.html"],
    ["decisions.md", "decisions.html"],
    ["devlog", "devlog.html"],
    ["devlog.md", "devlog.html"],
    ["notes", "notes.html"],
    ["notes.md", "notes.html"],
    ["symbols", "symbols.html"],
    ["symbols.md", "symbols.html"],
    ["links", "links.html"],
    ["links.md", "links.html"]
  ]);

  return routes.get(route);
}

function sourceHrefForFile(file: string, context: RenderContext): string | undefined {
  if (!file || path.isAbsolute(file) || file.startsWith("..") || file.includes("://") || file.startsWith("#")) {
    return undefined;
  }

  if (context.sourceBaseUrl) {
    return remoteSourceHref(file, context.sourceBaseUrl, context.root);
  }

  return `${"../".repeat(depthOf(context.currentFile) + 1)}${encodePath(toPosixPath(file))}`;
}

function remoteSourceHref(file: string, sourceBaseUrl: string, root: string): string {
  const normalizedFile = toPosixPath(file).replace(/^\.\//, "");
  const isDirectory = isDirectoryPath(root, normalizedFile);
  const baseUrl = isDirectory ? treeUrlForBase(sourceBaseUrl) : sourceBaseUrl;
  return `${baseUrl}${encodePath(normalizedFile)}`;
}

function treeUrlForBase(sourceBaseUrl: string): string {
  return sourceBaseUrl.replace("/blob/", "/tree/");
}

function isDirectoryPath(root: string, file: string): boolean {
  try {
    return fs.statSync(path.resolve(root, file)).isDirectory();
  } catch {
    return false;
  }
}

function searchIndexJs(model: SiteModel): string {
  const recordEntries: SearchEntry[] = model.flatRecords.map((record) => ({
    type: record.type,
    typeLabel: labelForType(record.type),
    id: record.id,
    title: recordTitle(record),
    summary: recordExcerpt(record),
    tags: displayTags(record),
    authority: record.authority,
    confidence: record.confidence,
    audienceLabel: audienceLabel(record),
    url: recordHref(record),
    text: recordSearchText(record)
  }));
  const workEntries: SearchEntry[] = showBeadsWork(model) && model.integrations.beads?.available
    ? [
      ...model.integrations.beads.ready,
      ...model.integrations.beads.in_progress,
      ...model.integrations.beads.recent_closed
    ].map((issue) => ({
      type: "work",
      typeLabel: "Project Work",
      id: `beads:${issue.id}`,
      title: issue.title,
      summary: beadsIssueSummary(issue),
      tags: issue.labels,
      authority: "system",
      confidence: "high",
      audienceLabel: "For developers",
      url: "work.html",
      text: [
        issue.id,
        issue.title,
        issue.status,
        issue.type,
        issue.priority,
        issue.assignee,
        issue.labels.join(" ")
      ].filter(Boolean).join(" ")
    }))
    : [];
  const entries = [...recordEntries, ...workEntries];

  return `/* Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run \`wk site\`. */
window.WIKIWIKI_SEARCH_INDEX = ${JSON.stringify(entries, null, 2)};
`;
}

function siteManifest(model: SiteModel) {
  return {
    generator: "Wikiwiki",
    generated_from: ".wikiwiki/records",
    command: "wk site",
    source_base_url: model.options.sourceBaseUrl ?? null,
    audience: model.audience,
    project_name: model.repoName,
    theme_file: ".wikiwiki/site-theme.json",
    pages: sitePages(model),
    ...(shouldReportIntegrations(model.integrations) ? { integrations: model.integrations } : {}),
    records: model.flatRecords.map((record) => ({
      type: record.type,
      id: record.id,
      title: recordTitle(record),
      url: recordHref(record)
    }))
  };
}

function sitePages(model: SiteModel): string[] {
  return siteStaticPageFileNames.filter((fileName) => fileName !== "work.html" || showBeadsWork(model));
}

function recordHref(record: AnyRecord): string {
  return `records/${record.type}/${safeFileName(record.id)}.html`;
}

function recordTitle(record: AnyRecord): string {
  if ("name" in record && typeof record.name === "string") {
    return record.name;
  }
  if ("title" in record && typeof record.title === "string") {
    return record.title;
  }
  if ("summary" in record && typeof record.summary === "string") {
    return record.summary;
  }
  if ("body" in record && typeof record.body === "string") {
    return record.body.slice(0, 80);
  }
  if ("relationship" in record && typeof record.relationship === "string") {
    return `${record.from} ${record.relationship} ${record.to}`;
  }
  return record.id;
}

function recordSummary(record: AnyRecord): string {
  if ("summary" in record && typeof record.summary === "string" && record.summary.trim()) {
    return record.summary.trim();
  }
  if ("decision" in record && typeof record.decision === "string" && record.decision.trim()) {
    return record.decision.trim();
  }
  if ("body" in record && typeof record.body === "string" && record.body.trim()) {
    return record.body.trim();
  }
  if ("relationship" in record && typeof record.relationship === "string") {
    return `${record.from} ${record.relationship} ${record.to}`;
  }
  return "No summary recorded.";
}

function recordExcerpt(record: AnyRecord): string {
  return conciseExcerpt(recordSummary(record));
}

function conciseExcerpt(text: string, maxLength = 150): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  if (normalized.length <= maxLength) {
    return normalized;
  }

  const window = normalized.slice(0, maxLength + 1);
  const sentenceEnds = [". ", "! ", "? "]
    .map((marker) => window.lastIndexOf(marker))
    .filter((index) => index >= 32);
  const sentenceEnd = sentenceEnds.length ? Math.max(...sentenceEnds) : -1;
  if (sentenceEnd >= 0) {
    return window.slice(0, sentenceEnd + 1).trim();
  }

  const wordBreak = window.lastIndexOf(" ");
  const end = wordBreak >= 72 ? wordBreak : maxLength;
  return `${normalized.slice(0, end).replace(/[\s,;:.-]+$/, "")}...`;
}

function recordSearchText(record: AnyRecord): string {
  return Object.values(record)
    .flatMap((value) => Array.isArray(value) ? value : [value])
    .filter((value): value is string => typeof value === "string")
    .join(" ");
}

function recordTimestamp(record: AnyRecord): string {
  if ("updated_at" in record && typeof record.updated_at === "string") {
    return record.updated_at;
  }

  return record.created_at;
}

function recordTags(record: AnyRecord): string[] {
  if ("tags" in record && Array.isArray(record.tags)) {
    return record.tags;
  }

  return [];
}

function relatedFiles(record: AnyRecord): string[] {
  if ("files" in record && Array.isArray(record.files)) {
    return record.files.map(toPosixPath);
  }

  if ("file" in record && typeof record.file === "string") {
    return [toPosixPath(record.file)];
  }

  return [];
}

function filterRecordsByAudience(records: RecordsByType, audience: SiteAudience): RecordsByType {
  const filtered = {} as RecordsByType;

  for (const type of recordTypes) {
    filtered[type] = records[type].filter((record) => recordMatchesAudience(record, audience)) as never;
  }

  return filtered;
}

function recordMatchesAudience(record: AnyRecord, audience: SiteAudience): boolean {
  if (audience === "all") {
    return true;
  }

  const recordAudienceValue = recordAudience(record);
  if (recordAudienceValue === "all" || recordAudienceValue === audience) {
    return true;
  }

  if (recordAudienceValue) {
    return false;
  }

  if (audience === "user" && (record.type === "symbol" || record.type === "link")) {
    return false;
  }

  return true;
}

function compareRecords(a: AnyRecord, b: AnyRecord): number {
  return a.type.localeCompare(b.type) ||
    recordTitle(a).localeCompare(recordTitle(b)) ||
    a.id.localeCompare(b.id);
}

function homepageRecords(model: SiteModel): AnyRecord[] {
  const curated = curatedRecords(model, ["concept", "decision", "note"], 6);
  if (curated.length > 0) {
    return curated;
  }

  return curatedRecords(model, recordTypes, 6);
}

function userGuideRecordsFor(model: SiteModel): AnyRecord[] {
  return model.flatRecords
    .filter((record) => ["concept", "note", "decision"].includes(record.type))
    .filter(isUserGuideRecord)
    .sort(compareRecordsForCuration)
    .slice(0, 8);
}

function curatedRecords(model: SiteModel, types: readonly RecordType[], limit: number): AnyRecord[] {
  const allowedTypes = new Set(types);
  return model.flatRecords
    .filter((record) => allowedTypes.has(record.type))
    .sort(compareRecordsForCuration)
    .slice(0, limit);
}

function takeUnusedRecords(records: readonly AnyRecord[], usedIds: Set<string>, limit: number): AnyRecord[] {
  const result: AnyRecord[] = [];
  for (const record of records) {
    if (usedIds.has(record.id)) {
      continue;
    }

    usedIds.add(record.id);
    result.push(record);
    if (result.length >= limit) {
      break;
    }
  }

  return result;
}

function compareRecordsForCuration(a: AnyRecord, b: AnyRecord): number {
  return curationScore(b) - curationScore(a) ||
    recordTitle(a).localeCompare(recordTitle(b)) ||
    a.id.localeCompare(b.id);
}

function curationScore(record: AnyRecord): number {
  let score = 0;
  const tags = recordTags(record).map((tag) => tag.toLowerCase());

  if (tags.includes(audienceTags.user) || tags.includes(audienceTags.all)) {
    score += 16;
  }
  if (tags.includes(audienceTags.developer)) {
    score -= 4;
  }
  if (isUserGuideRecord(record)) {
    score += 28;
  }
  if (tags.some((tag) => ["pinned", "homepage", "start-here", "overview", "guide"].includes(tag))) {
    score += 80;
  }
  if (record.authority === "user") {
    score += 35;
  }
  if (record.confidence === "high") {
    score += 18;
  }
  if (record.type === "concept") {
    score += 24;
  }
  if (record.type === "decision") {
    score += 20;
  }
  if (record.type === "note") {
    score += 6;
  }
  if (record.type === "event") {
    score -= tags.some((tag) => ["release", "milestone", "launch"].includes(tag)) ? 6 : 28;
  }
  if (tags.some((tag) => ["internal", "maintenance", "implementation", "package", "ci", "devlog"].includes(tag))) {
    score -= 12;
  }

  return score;
}

function isUserGuideRecord(record: AnyRecord): boolean {
  const tags = recordTags(record).map((tag) => tag.toLowerCase());
  return tags.some((tag) => (userMaterialTags as readonly string[]).includes(tag)) ||
    tags.includes(audienceTags.user);
}

function statsTypes(model: SiteModel): RecordType[] {
  const preferred: RecordType[] = ["concept", "decision", "event", "note"];
  const visible = preferred.filter((type) => model.counts[type] > 0);
  if (visible.length > 0) {
    return visible;
  }

  return recordTypes.filter((type) => model.counts[type] > 0).slice(0, 4);
}

function showBeadsWork(model: SiteModel): boolean {
  const beads = model.integrations.beads;
  return model.audience !== "user" &&
    Boolean(beads?.detected) &&
    Boolean(beads?.enabled);
}

function beadsNavCount(beads: BeadsIntegrationSummary | undefined): number | undefined {
  if (!beads?.available) {
    return undefined;
  }

  return beads.counts.ready + beads.counts.in_progress;
}

function beadsIssueSummary(issue: BeadsIssueSummary): string {
  return [
    issue.status,
    issue.type,
    issue.priority,
    issue.assignee ? `assigned to ${issue.assignee}` : ""
  ].filter(Boolean).join(" · ") || "Beads work item.";
}

function tagList(tags: string[]): string {
  if (tags.length === 0) {
    return "";
  }

  return `<span class="tag-list">${tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join("")}</span>`;
}

function displayTags(record: AnyRecord): string[] {
  return recordTags(record).filter((tag) => !isAudienceTag(tag));
}

function isAudienceTag(tag: string): boolean {
  const normalized = tag.toLowerCase();
  return normalized === audienceTags.user ||
    normalized === audienceTags.developer ||
    normalized === audienceTags.all;
}

function recordAudience(record: AnyRecord): SiteAudience | undefined {
  const tags = recordTags(record).map((tag) => tag.toLowerCase());
  if (tags.includes(audienceTags.user)) {
    return "user";
  }
  if (tags.includes(audienceTags.developer)) {
    return "developer";
  }
  if (tags.includes(audienceTags.all)) {
    return "all";
  }

  return undefined;
}

function audienceLabel(record: AnyRecord): string {
  const audience = recordAudience(record);
  if (audience === "user") {
    return "For users";
  }
  if (audience === "developer") {
    return "For developers";
  }
  if (audience === "all") {
    return "For everyone";
  }

  return "";
}

function audienceIntro(audience: SiteAudience): string {
  if (audience === "user") {
    return "This view emphasizes getting started, product orientation, privacy, FAQ, and troubleshooting while keeping developer-only records out of the way.";
  }
  if (audience === "developer") {
    return "This view emphasizes architecture, decisions, source symbols, generated-file workflow, and maintainer context.";
  }

  return "Start with curated guides, then browse source-backed user and developer knowledge when you need more detail.";
}

function emptyState(message: string): string {
  return `<div class="empty-state">${escapeHtml(message)}</div>`;
}

function labelForType(type: RecordType): string {
  if (type === "event") {
    return "Devlog";
  }

  return type[0].toUpperCase() + type.slice(1);
}

function initialsForName(value: string): string {
  const words = value
    .replace(/[_-]+/g, " ")
    .split(/\s+/)
    .map((word) => word.trim())
    .filter(Boolean);
  const initials = words.length >= 2
    ? `${words[0][0]}${words[1][0]}`
    : (words[0] ?? "W").slice(0, 2);

  return initials.toUpperCase();
}

function formatDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toISOString().slice(0, 10);
}

function hrefFrom(currentFile: string, targetFile: string): string {
  const currentDir = path.posix.dirname(currentFile);
  const relative = currentDir === "."
    ? targetFile
    : path.posix.relative(currentDir, targetFile);
  return escapeAttribute(relative || path.posix.basename(targetFile));
}

function relativePrefix(fileName: string): string {
  return "../".repeat(depthOf(fileName));
}

function depthOf(fileName: string): number {
  return fileName.split("/").length - 1;
}

function safeFileName(value: string): string {
  return value.replace(/[^a-z0-9._-]+/gi, "-");
}

function toPosixPath(value: string): string {
  return value.replace(/\\/g, "/");
}

function encodePath(value: string): string {
  return value.split("/").map(encodeURIComponent).join("/");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value);
}

function projectThemeCss(theme: WikiwikiSiteTheme): string {
  const guardedTheme = themeWithContrastGuardrails(theme);
  const variables: [keyof WikiwikiSiteTheme, string][] = [
    ["accent", "--accent"],
    ["accent_strong", "--accent-strong"],
    ["bg", "--bg"],
    ["panel", "--panel"],
    ["panel_soft", "--panel-soft"],
    ["text", "--text"],
    ["muted", "--muted"],
    ["border", "--border"],
    ["code_bg", "--code-bg"],
    ["radius", "--radius"],
    ["font_family", "--font-family"]
  ];
  const lines = variables
    .flatMap(([key, variable]) => {
      const value = guardedTheme.theme[key]?.trim();
      return value ? [`  ${variable}: ${cssValue(value)};`] : [];
    });

  if (lines.length === 0) {
    return "/* Optional project theme. Add .wikiwiki/site-theme.json to override CSS custom properties. */\n";
  }

  const comments = guardedTheme.comments.length
    ? `\n${guardedTheme.comments.map((comment) => `/* ${comment} */`).join("\n")}`
    : "";
  return `/* Generated from .wikiwiki/site-theme.json. Edit the theme file, then run \`wk site\`. */${comments}
:root {
${lines.join("\n")}
}
`;
}

function themeWithContrastGuardrails(theme: WikiwikiSiteTheme): {
  theme: WikiwikiSiteTheme;
  comments: string[];
} {
  const guarded: WikiwikiSiteTheme = { ...theme };
  const comments: string[] = [];
  const bg = parseHexColor(guarded.bg);

  if (bg && !guarded.panel && relativeLuminance(bg) < 0.18) {
    guarded.panel = "#111827";
    guarded.panel_soft = guarded.panel_soft ?? "#1f2937";
    guarded.text = guarded.text ?? "#f8fafc";
    guarded.muted = guarded.muted ?? "#cbd5e1";
    guarded.border = guarded.border ?? "#334155";
    guarded.code_bg = guarded.code_bg ?? "#0f172a";
    comments.push("Applied dark-theme surface defaults so text remains readable.");
  }

  const panel = parseHexColor(guarded.panel ?? "#ffffff");
  const text = parseHexColor(guarded.text ?? "#242521");
  if (panel && text && contrastRatio(panel, text) < 4.5) {
    guarded.text = readableTextFor(panel);
    comments.push("Adjusted --text for readable contrast against --panel.");
  }

  const muted = parseHexColor(guarded.muted ?? "#63675e");
  const guardedPanel = parseHexColor(guarded.panel ?? "#ffffff");
  if (guardedPanel && muted && contrastRatio(guardedPanel, muted) < 3) {
    guarded.muted = relativeLuminance(guardedPanel) > 0.5 ? "#4b5563" : "#cbd5e1";
    comments.push("Adjusted --muted for readable contrast against --panel.");
  }

  return { theme: guarded, comments };
}

type Rgb = {
  r: number;
  g: number;
  b: number;
};

function parseHexColor(value: string | undefined): Rgb | undefined {
  const trimmed = value?.trim();
  if (!trimmed) {
    return undefined;
  }

  const match = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(trimmed);
  if (!match) {
    return undefined;
  }

  const hex = match[1].length === 3
    ? match[1].split("").map((part) => `${part}${part}`).join("")
    : match[1];

  return {
    r: Number.parseInt(hex.slice(0, 2), 16),
    g: Number.parseInt(hex.slice(2, 4), 16),
    b: Number.parseInt(hex.slice(4, 6), 16)
  };
}

function contrastRatio(a: Rgb, b: Rgb): number {
  const lighter = Math.max(relativeLuminance(a), relativeLuminance(b));
  const darker = Math.min(relativeLuminance(a), relativeLuminance(b));
  return (lighter + 0.05) / (darker + 0.05);
}

function relativeLuminance(color: Rgb): number {
  const [r, g, b] = [color.r, color.g, color.b].map((channel) => {
    const value = channel / 255;
    return value <= 0.03928
      ? value / 12.92
      : ((value + 0.055) / 1.055) ** 2.4;
  });

  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function readableTextFor(background: Rgb): string {
  return relativeLuminance(background) > 0.5 ? "#111827" : "#f8fafc";
}

function cssValue(value: string): string {
  return value.replace(/[;\n\r]/g, "").trim();
}

function siteCss(): string {
  return `/* Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run \`wk site\`. */
:root {
  color-scheme: light;
  --bg: #f7f7f4;
  --panel: #ffffff;
  --panel-soft: #f0f2ed;
  --text: #242521;
  --muted: #63675e;
  --border: #dcdfd6;
  --accent: #246b62;
  --accent-strong: #163f3a;
  --pink: #c43f7d;
  --code-bg: #eceee8;
  --shadow: 0 18px 45px rgba(35, 38, 31, 0.08);
  --radius: 8px;
  --font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: var(--font-family);
  line-height: 1.55;
}

a {
  color: var(--accent);
  text-decoration-thickness: 0.08em;
  text-underline-offset: 0.18em;
}

code {
  border-radius: 5px;
  background: var(--code-bg);
  padding: 0.12rem 0.32rem;
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
  font-size: 0.9em;
}

.skip-link {
  position: absolute;
  left: 1rem;
  top: -4rem;
  z-index: 10;
  border-radius: 6px;
  background: var(--text);
  color: white;
  padding: 0.55rem 0.8rem;
}

.skip-link:focus {
  top: 1rem;
}

.site-shell {
  display: grid;
  grid-template-columns: 280px minmax(0, 1fr);
  min-height: 100vh;
}

.sidebar {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
  border-right: 1px solid var(--border);
  background: rgba(255, 255, 255, 0.82);
  padding: 1.1rem;
}

.sidebar-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.8rem;
}

.brand {
  display: flex;
  align-items: center;
  gap: 0.7rem;
  color: var(--text);
  text-decoration: none;
}

.brand-mark {
  display: grid;
  place-items: center;
  width: 2.4rem;
  height: 2.4rem;
  border-radius: var(--radius);
  background: linear-gradient(135deg, var(--accent), var(--accent-strong));
  color: white;
  font-size: 0.85rem;
  font-weight: 800;
  letter-spacing: 0;
}

.brand strong,
.brand small {
  display: block;
}

.brand small,
.nav-heading,
.eyebrow {
  color: var(--muted);
  font-size: 0.76rem;
  font-weight: 700;
  letter-spacing: 0;
  text-transform: uppercase;
}

.nav-toggle {
  display: none;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--panel);
  color: var(--text);
  padding: 0.45rem 0.65rem;
  font: inherit;
  font-weight: 700;
}

input[type="search"] {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--panel);
  color: var(--text);
  padding: 0.7rem 0.78rem;
  font: inherit;
}

input[type="search"]:focus {
  border-color: var(--accent);
  outline: 3px solid rgba(36, 107, 98, 0.16);
}

.nav {
  display: grid;
  gap: 0.2rem;
  margin-top: 1.2rem;
}

.nav-heading {
  margin: 1rem 0 0.25rem;
}

.nav-link {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.7rem;
  border-radius: var(--radius);
  color: var(--text);
  padding: 0.5rem 0.58rem;
  text-decoration: none;
}

.nav-link:hover,
.nav-link.active {
  background: var(--panel-soft);
  color: var(--accent-strong);
}

.nav-link span {
  min-width: 1.7rem;
  border: 1px solid var(--border);
  border-radius: 999px;
  color: var(--muted);
  padding: 0.02rem 0.45rem;
  text-align: center;
  font-size: 0.76rem;
}

.content {
  width: min(100%, 1120px);
  padding: 2.3rem clamp(1rem, 4vw, 4rem) 4rem;
}

.page-header {
  margin-bottom: 1.5rem;
}

.page-header h1 {
  margin: 0.15rem 0 0.45rem;
  font-size: clamp(2rem, 4vw, 3.8rem);
  line-height: 1;
}

.page-header p {
  max-width: 760px;
  color: var(--muted);
  font-size: 1.08rem;
}

.hero-panel {
  display: grid;
  grid-template-columns: minmax(0, 1.5fr) minmax(260px, 0.9fr);
  gap: 1rem;
  align-items: stretch;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: linear-gradient(135deg, #ffffff 0%, #f4f6f0 100%);
  box-shadow: var(--shadow);
  padding: clamp(1.1rem, 3vw, 2rem);
}

.hero-panel h2,
.section-heading h2 {
  margin: 0.2rem 0 0;
  font-size: clamp(1.35rem, 2vw, 2rem);
  line-height: 1.15;
}

.hero-panel p {
  max-width: 680px;
  color: var(--muted);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.7rem;
  margin: 0;
}

.stats-grid div {
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: rgba(255, 255, 255, 0.72);
  padding: 0.9rem;
}

.stats-grid dt {
  color: var(--muted);
  font-size: 0.8rem;
}

.stats-grid dd {
  margin: 0.1rem 0 0;
  font-size: 1.7rem;
  font-weight: 800;
}

.section {
  margin-top: 2rem;
}

.section-heading {
  margin-bottom: 0.9rem;
}

.card-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.85rem;
}

.card-grid.compact {
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.section-card,
.record-card,
.search-result,
.empty-state,
.search-panel,
.record-meta,
.sources-panel {
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--panel);
}

.section-card {
  display: block;
  min-height: 9.5rem;
  color: var(--text);
  padding: 1rem;
  text-decoration: none;
}

.section-card:hover,
.record-card:hover,
.search-result:hover {
  border-color: rgba(36, 107, 98, 0.4);
  box-shadow: var(--shadow);
}

.section-card span {
  color: var(--pink);
  font-size: 0.8rem;
  font-weight: 700;
}

.section-card strong {
  display: block;
  margin: 0.35rem 0;
  font-size: 1.25rem;
}

.section-card p,
.record-card p,
.search-result p {
  margin-bottom: 0;
  color: var(--muted);
}

.record-list {
  display: grid;
  gap: 0.75rem;
}

.record-card,
.search-result {
  padding: 1rem;
}

.record-card-top,
.record-card footer,
.record-title-row,
.search-result footer {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.5rem;
}

.record-card-top {
  justify-content: space-between;
}

.record-card h3,
.search-result h3 {
  margin: 0.6rem 0 0.25rem;
  font-size: 1.15rem;
}

.record-card h3 a,
.search-result h3 a {
  color: var(--text);
}

.record-card footer,
.search-result footer {
  justify-content: space-between;
  margin-top: 0.85rem;
}

.type-badge,
.audience-badge,
.confidence,
.tag-list span {
  display: inline-flex;
  align-items: center;
  min-height: 1.45rem;
  border-radius: 999px;
  padding: 0.12rem 0.5rem;
  font-size: 0.76rem;
  font-weight: 700;
}

.type-badge {
  background: #e5f0ed;
  color: var(--accent-strong);
}

.audience-badge {
  background: var(--panel-soft);
  color: var(--muted);
}

.confidence {
  background: var(--panel-soft);
  color: var(--muted);
}

.confidence.high {
  background: #e7f3df;
  color: #2d5c1f;
}

.confidence.low {
  background: #f5e7df;
  color: #7a3c1d;
}

.tag-list {
  display: inline-flex;
  flex-wrap: wrap;
  gap: 0.3rem;
}

.tag-list span {
  background: #f8e8f1;
  color: #743050;
}

.record-page {
  max-width: 860px;
}

.breadcrumbs {
  display: flex;
  gap: 0.45rem;
  margin-bottom: 1rem;
  color: var(--muted);
  font-size: 0.9rem;
}

.prose {
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--panel);
  padding: clamp(1rem, 3vw, 1.6rem);
}

.prose h2 {
  margin: 1.3rem 0 0.3rem;
  font-size: 1.25rem;
}

.prose h2:first-child {
  margin-top: 0;
}

.prose p,
.prose ul {
  color: #373933;
}

.record-meta {
  margin-top: 1rem;
  padding: 0.75rem 1rem;
}

.sources-panel {
  margin-top: 1rem;
  padding: 1rem;
}

.sources-panel h2 {
  margin: 0 0 0.5rem;
  font-size: 1rem;
}

.sources-panel ul {
  margin: 0;
  padding-left: 1.1rem;
}

.record-meta summary {
  cursor: pointer;
  font-weight: 700;
}

.record-meta dl {
  display: grid;
  gap: 0.55rem;
  margin: 0.8rem 0 0;
}

.record-meta dl div {
  display: grid;
  grid-template-columns: 7rem minmax(0, 1fr);
  gap: 0.75rem;
}

.record-meta dt {
  color: var(--muted);
  font-weight: 700;
}

.record-meta dd {
  margin: 0;
}

.record-meta ul {
  margin: 0;
  padding-left: 1.1rem;
}

.search-panel {
  padding: 1rem;
}

.search-panel label {
  display: grid;
  gap: 0.45rem;
  font-weight: 700;
}

.search-results {
  display: grid;
  gap: 0.75rem;
  margin-top: 1rem;
}

.empty-state {
  color: var(--muted);
  padding: 1rem;
}

.empty-state strong {
  display: block;
  color: var(--text);
  margin-bottom: 0.2rem;
}

.site-footer {
  margin-top: 3rem;
  border-top: 1px solid var(--border);
  color: var(--muted);
  padding-top: 1rem;
  font-size: 0.9rem;
}

@media (max-width: 860px) {
  .site-shell {
    grid-template-columns: 1fr;
  }

  .sidebar {
    position: static;
    height: auto;
    border-bottom: 1px solid var(--border);
    border-right: 0;
    padding: 0.85rem 1rem;
  }

  .nav-toggle {
    display: inline-flex;
  }

  .sidebar-nav {
    display: none;
  }

  .sidebar-nav.open {
    display: block;
  }

  .nav {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .nav-heading {
    grid-column: 1 / -1;
  }

  .hero-panel,
  .card-grid,
  .card-grid.compact {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 560px) {
  .content {
    padding: 1.4rem 1rem 3rem;
  }

  .nav {
    grid-template-columns: 1fr;
  }

  .stats-grid {
    grid-template-columns: 1fr;
  }

  .record-meta dl div {
    grid-template-columns: 1fr;
    gap: 0.1rem;
  }
}

@media print {
  :root {
    --bg: #ffffff;
    --panel: #ffffff;
    --shadow: none;
  }

  body {
    background: #ffffff;
  }

  .site-shell {
    display: block;
  }

  .sidebar,
  .skip-link,
  .nav-toggle,
  script {
    display: none !important;
  }

  .content {
    width: auto;
    padding: 0;
  }

  .page-header,
  .hero-panel,
  .section,
  .section-card,
  .record-card,
  .search-result,
  .prose,
  .record-meta,
  .sources-panel,
  .site-footer {
    break-inside: avoid;
    page-break-inside: avoid;
  }

  .hero-panel,
  .section-card,
  .record-card,
  .search-result,
  .prose,
  .record-meta,
  .sources-panel {
    box-shadow: none;
  }

  a {
    color: inherit;
  }
}
`;
}

function siteJs(): string {
  return `/* Generated by Wikiwiki from .wikiwiki/records. Edit structured records instead, then run \`wk site\`. */
(function () {
  const entries = Array.isArray(window.WIKIWIKI_SEARCH_INDEX) ? window.WIKIWIKI_SEARCH_INDEX : [];

  function escapeHtml(value) {
    return String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function normalize(value) {
    return String(value || "").toLowerCase();
  }

  function resultHtml(entry) {
    const tags = Array.isArray(entry.tags) && entry.tags.length
      ? '<span class="tag-list">' + entry.tags.slice(0, 6).map((tag) => '<span>' + escapeHtml(tag) + '</span>').join("") + '</span>'
      : "";
    const audience = entry.audienceLabel
      ? '<span class="audience-badge">' + escapeHtml(entry.audienceLabel) + '</span>'
      : "";
    return '<article class="search-result">' +
      '<div class="record-card-top"><span class="type-badge">' + escapeHtml(entry.typeLabel || entry.type) + '</span>' + audience + '</div>' +
      '<h3><a href="' + encodeURI(entry.url) + '">' + escapeHtml(entry.title) + '</a></h3>' +
      '<p>' + escapeHtml(entry.summary) + '</p>' +
      (tags ? '<footer>' + tags + '</footer>' : '') +
    '</article>';
  }

  function search(query) {
    const normalizedQuery = normalize(query).trim();
    if (!normalizedQuery) {
      return [];
    }

    const terms = normalizedQuery.split(/\\s+/).filter(Boolean);
    return entries
      .map((entry) => {
        const text = normalize([entry.title, entry.summary, entry.text, entry.id, entry.type, (entry.tags || []).join(" ")].join(" "));
        const matchedTerms = terms.filter((term) => text.includes(term)).length;
        return { entry, matchedTerms };
      })
      .filter((result) => result.matchedTerms > 0)
      .sort((a, b) => b.matchedTerms - a.matchedTerms || a.entry.title.localeCompare(b.entry.title))
      .slice(0, 50)
      .map((result) => result.entry);
  }

  function updateSearchPage(query) {
    const resultsRoot = document.querySelector("[data-search-results]");
    if (!resultsRoot) {
      return;
    }

    if (!normalize(query).trim()) {
      resultsRoot.innerHTML = '<div class="empty-state"><strong>Search is ready.</strong><p>Try a concept, decision, tag, or source file. Results stay local to this generated site.</p></div>';
      return;
    }

    const matches = search(query);
    resultsRoot.innerHTML = matches.length
      ? matches.map(resultHtml).join("")
      : '<div class="empty-state">No matching records.</div>';
  }

  const params = new URLSearchParams(window.location.search);
  const initialQuery = params.get("q") || "";
  const pageInput = document.querySelector("[data-search-page-input]");
  if (pageInput) {
    pageInput.value = initialQuery;
    pageInput.addEventListener("input", () => updateSearchPage(pageInput.value));
    updateSearchPage(initialQuery);
  }

  document.querySelectorAll("[data-site-search]").forEach((input) => {
    input.addEventListener("keydown", (event) => {
      if (event.key !== "Enter") {
        return;
      }
      event.preventDefault();
      const target = input.getAttribute("data-search-target") || "search.html";
      const query = input.value ? "?q=" + encodeURIComponent(input.value) : "";
      window.location.href = target + query;
    });
  });

  document.querySelectorAll("[data-nav-toggle]").forEach((button) => {
    button.addEventListener("click", () => {
      const nav = document.querySelector("[data-sidebar-nav]");
      if (!nav) {
        return;
      }
      const isOpen = nav.classList.toggle("open");
      button.setAttribute("aria-expanded", isOpen ? "true" : "false");
    });
  });
}());
`;
}
